### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by IL4Miy** [pqina/vue-filepond#1]
I imported the package in my project and use the sample code.
I get the following error when starting the application:

_Uncaught SyntaxError: Unexpected token <
/projectnames/node_modules/vue-filepond/index.vue_

I use the [electron-vue-boilertemplate](https://github.com/SimulatedGREG/electron-vue).

**Comment by rikschennink** [comment]
@IL4Miy That shouldn't be happening, let me quickly run some tests!

**Comment by IL4Miy** [comment]
@rikschennink Yes the `<template>` tag is the problem.

**Comment by rikschennink** [comment]
@IL4Miy should a vue component be precompiled then? 

Maybe it's better to use the `Vue.component` method instead of what I've got now.
```vue
// register
Vue.component('my-component', {
  template: '<div>A custom component!</div>'
})
```

**Comment by IL4Miy** [comment]
@rikschennink Seems, that the vue-component can't be compiled. 
Maybe it can be compiled with webpack.
Another approach could be to precompile your component and publish the JS component.
https://github.com/vuejs/vue-component-compiler

**Comment by rikschennink** [comment]
@IL4Miy I'm switching to `render` function now, that should fix the issue as compilation is no longer needed.

**Comment by rikschennink** [comment]
@IL4Miy I've just published version `1.0.1` of `vue-filepond`. Can you test if the switch to the render function solves the problem?

**Comment by IL4Miy** [comment]
@rikschennink I now get the error, that 'import' could not be found.
But I solved the problem. In my webpack config I added `vue-filepond` to the whitelist. (`let whiteListedModules = ['vue', 'vue-filepond']`).
[Here](https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals) is the explanation.

I also tried the version 1.0.0 of vue-filepond and it works also fine with the change in the webpack config. Maybe you could add this hint in the readme?

**Comment by rikschennink** [comment]
Thanks, good to know! Would be nice if no special settings were required. I'll do some research on it next week. It's probably because of ES6 syntax. Could simply replace `import` it with `require`, but there might be some other ES6 features I'm using that will have to be replaced.

**Comment by weislanes** [comment]
Hey, not the exact same error but may have a similar cause:

When building for production with webpack it spits out this error:

```
ERROR in static/js/vendor.d0250f643c050ea78c22.js from UglifyJs
Unexpected token: operator (>) [./~/vue-filepond/index.js:34,0][static/js/vendor.d0250f643c050ea78c22.js:60755,43]
```

The files are still built  but they are not uglified/compressed.

**Comment by rikschennink** [comment]
@weislanes I think this has to do with the arrow function on that line (UglifyJS cannot deal with that), are you using Bable to transpile first?

**Comment by rikschennink** [comment]
I've added build targets to the package, should solve the issue

**Comment by weislanes** [comment]
Thanks
