### ISSUE TITLE
dropOnPage isn't working

### ISSUE THREAD

**Issue by Hellek** [pqina/vue-filepond#10]
This code change dropOnPage prop to true, but file dropping isn't working
```
<FilePond
	ref="pond"
	v-bind:files="myFiles"
	:allowMultiple="true"
	:allowBrowse="true"
	:allowDrop="true"
	:dropOnPage="true"
/>
```

**Comment by rikschennink** [comment]
Hi! You have to set `:dropOnElement` to `false` to allow dropping on the page.

**Comment by Hellek** [comment]
Oooh. Yep, it works, but not as expected. I thought this option exteds dropzone to whole page.

**Comment by rikschennink** [comment]
@Hellek Visually there should be no change, but FilePond should catch files dropped outside of the drop area.

**Comment by Hellek** [comment]
![2018-05-01_19-32-43](https://user-images.githubusercontent.com/7388712/39482196-b60a1892-4d76-11e8-982c-9cae58eea64e.png)
![2018-05-01_19-34-03](https://user-images.githubusercontent.com/7388712/39482197-b62a9b8a-4d76-11e8-9990-c1f4e137d53e.png)
:dropOnPage="" examples on false and on true.
True - forbid attach
False - don't forbid, but dropping outside of dropzone area cause not effect.

Is is right, that Filepond shoud catch drop Event even it cause somewhere on the page?

I'm trying to do this with
```
window.addEventListener("drop", function(e) {
   console.log("drop", e);
   e = e || event;
   e.preventDefault();
}, false);
```
Intercept an event and throw it to filepond...

**Comment by Hellek** [comment]
Problem is solved)
Need to use both props
:dropOnElement="false"
:dropOnPage="true"

In this case works both modes - page drop and dropzone drop

**Comment by rikschennink** [comment]
That was what I meant with my first reply 👍

When using multiple drop areas on the same page you need to set `dropOnElement` to true otherwise they will all catch the same files.

**Comment by Herz3h** [comment]
Is there a workaround to both have dropOnPage=true and having multiple fileponds @rikschennink ?

**Comment by rikschennink** [comment]
@Herz3h FilePond would not know which instance to load to. I advise to set it to false and listen for the drop file yourself, you can then pipe the file to the correct filepond instance.

**Comment by Herz3h** [comment]
Thats a good idea. For now I found this way:

```javascript
            beforeAddFile: (item) =>
            {
                return this.$container.hasClass('active');
            }
```
