### ISSUE TITLE
Feature request: Having global headers

### ISSUE THREAD

**Issue by Geowan** [pqina/vue-filepond#102]
Currently all headers have to be set on each server object that is you have to set headers for process, revert restore and load differently. In my case the only headers am setting are authorization tokens which am forced to add them like

         server: {
                url: '/api/v1/settings/logo/',
                process: {
                    url: 'upload',
                    method: 'POST',
                },
                revert: {
                    url: 'delete',
                    headers: {
                        'Authorization': 'Bearer ' + tokenservice.gettoken(tokenservice.accesstoken),
                    },
                    method: 'POST',
                },
                restore: {
                    url: 'restore',
                    headers: {
                        'Authorization': 'Bearer ' + tokenservice.gettoken(tokenservice.accesstoken),
                   },
                    method: 'POST',
                },
                load: {
                    url: 'load',
                    headers: {
                        'Authorization': 'Bearer ' + tokenservice.gettoken(tokenservice.accesstoken),
                    },
                    method: 'GET',
                },
                fetch: {
                    url: 'fetch',
                    headers: {
                        'Authorization': 'Bearer ' + tokenservice.gettoken(tokenservice.accesstoken),
                    },
                    method: 'GET',
                },
            }

As you can see from all endpoints there is a repetation of the Authorization headers. 
Cant we have an option to add global headers which will reduce repetition in the code

SO something like

          server: {
                url: '/api/v1/settings/logo/',
                globalHeaders: {
                        'Authorization': 'Bearer ' + tokenservice.gettoken(tokenservice.accesstoken),
                 },
                process:'upload',
                revert: 'delete',
                restore:'restore' ,
                load: 'load',
                fetch:  'fetch',
            }

Then if there is a need to set different headers for different parts then one can override as earlier.

**Comment by rikschennink** [comment]
Now available in FilePond `4.5.0`

`npm i filepond@latest --save`

```js
server: {
    headers: {
        // headers to use for all end points
    }
}
```
