### ISSUE TITLE
Revert problem

### ISSUE THREAD

**Issue by usb248** [pqina/vue-filepond#106]
Hi 

Revert function doesn't send always correctly id

### How to reproduce
set a file (via :files prop), wait load function done, and click on revert button.
The request doesn't send an id, but just the value

### Expected behaviour
Delete request always send serverId like this : {id:  the_unique_id} (json string) and not just the_unique_id (plain value)
I have to do : data: isJsonString(serverId) ? serverId : { id: serverId }, in my revert function with $axios...

| Environment  | Version
|------------- | -----------
| OS           |  Windows
| Device       | Laptop
| Browser      | last FF

**Comment by rikschennink** [comment]
Does your server return a unique id?

**Comment by usb248** [comment]
Yes when i revert, my server return a json.
But i don't understand why filepond send as plain text when i revert a file which is loaded by my load endpoint (file binary data)

**Comment by rikschennink** [comment]
I think it's best if you read the server docs: https://pqina.nl/filepond/docs/patterns/api/server/

**Comment by usb248** [comment]
Already read. I only see `X-Content-Transfer-Id` header but it's not what I need
