### ISSUE TITLE
Retrieve file without uploading to the server

### ISSUE THREAD

**Issue by MuizU** [pqina/vue-filepond#111]
Hi, currently working on file-pond with no-ssr. I want to upload the file after a button click. How do I retrieve the file object from an on change function?

**Comment by rikschennink** [comment]
you can use the `onupdatefiles` to access the current file items array, each file item has a `file` property

**Comment by rikschennink** [comment]
closed because inactive

**Comment by vesper8** [comment]
@MuizU @rikschennink I also want to only upload the files once a button is clicked and other form data is sent. You explain above how to get the array of files that need to be uploaded. However how do I disable the auto-uploading to begin with? Currently as soon as I add any file it immediately fires the upload API call

**Comment by rikschennink** [comment]
@vesper8 remove the `server` prop and files aren't uploaded.
