### ISSUE TITLE
Unable to have limit the maximum file size

### ISSUE THREAD

**Issue by MuizU** [pqina/vue-filepond#112]
Summary
Hi, I'm having an issue with the file limit validation I have limited the file to 10 MB but I am still able to upload files greater than 10MB. It does validate for files based on the file type

![Capture](https://user-images.githubusercontent.com/35157872/66809855-c6e51b80-ef4b-11e9-8996-b6e8c25fc70e.PNG)

![Capture1](https://user-images.githubusercontent.com/35157872/66810224-6f937b00-ef4c-11e9-88cd-828760d67dc7.PNG)

Below is the code that I use as another component
```html
 <client-only>
    <FilePond
      name="test"
      ref="newPond"
      :allow-multiple="false"
      :accepted-file-types="vueTypes"
      v-on:addfile="AddANewFile"
      maxFileSize="10MB"
      v-on:removefile=RemoveFile"
      :files="fileObj"
      @init=fileInit"
    />
  </client-only>

```
### How to reproduce
Run vue-filepond in Brave browser Version 0.67.124 

### Expected behaviour

When uploading it should validate files greater than 10MB

### Additional information

| Environment  | Version
|------------- | -----------
| OS           |  Windows 
| Device       | Desktop.
| Browser      | Brave Version 0.67.124

**Comment by rikschennink** [comment]
Have you added the file-validate-size plugin?

**Comment by MuizU** [comment]
> Have you added the file-validate-size plugin?

I added it. It works now
