### ISSUE TITLE
revert is not called during use removeFile()

### ISSUE THREAD

**Issue by voidEvgeny** [pqina/vue-filepond#113]
Hello, files are deleted, but the revert request to the server does not come.

```
let files = this.$refs.pond[0].$children[0].getFiles()
files.forEach(file => {
     this.$refs.pond[0].$children[0].removeFile(file)
})
```

The revert request comes only when I click the delete button on the file.

How can I call revert manually to delete the file on the server? Thanks!
  
```
server: {
          restore: "?load=",
          url: "/api/products",
          headers: {
            "X-CSRF-TOKEN": document.head.querySelector('meta[name="csrf-token"]').content
          }
```

```
<file-pond
      name="file"
      class-name=""
      ref="pond"
      :label-idle="label"
      :allow-multiple="multiple"
      :max-files="maxFiles"
      :accepted-file-types="fileType"
      :allow-revert="true"
      :force-revert="true"
      @warning="onWarning"
      @init="onInit"
      @processfilerevert="onRevert"
      @updatefiles="onUpdateFiles"
      @removefile="onRemoveFile"
      @processfile="onAddFile"
      :required="true"
      item-insert-location="after"
/>
```

**Comment by rikschennink** [comment]
Looking at the server config it seems there is no 'revert' end point.

**Comment by voidEvgeny** [comment]
I use default revert point. When click on the cross, the file is deleted from the server, but when using the removeFile() function, file deletion from the server does not occur. How to fix it?

**Comment by rikschennink** [comment]
The remove file is not enabled by default and can only be set to a custom function as it's a security risk to allow removal of local files.

**Comment by voidEvgeny** [comment]
But I do not use the “local” file type.  I use the boot type “input” and “limbo”.  Why is revert not called when calling the removeFile() function?

**Comment by voidEvgeny** [comment]
solved the problem like that:
```
  beforeDestroy() {
    const files = this.$refs.pond.getFiles()
    files.forEach(file => {
      if (file.origin === 1 || file.origin === 2) {
        axios.delete('/api/products', {data: file.serverId})
        this.$refs.pond.removeFile(file)
      }
    })
  },
```

**Comment by lokpro** [comment]
> solved the problem like that:
> 
> ```
>     const files = this.$refs.pond.getFiles()
>     files.forEach(file => {
>       if (file.origin === 1 || file.origin === 2) {
>         axios.delete('/api/products', {data: file.serverId})
>         this.$refs.pond.removeFile(file)
>       }
>     })
> ```

pond.removeFiles({ revert: true });

I got this to work, hinted by https://github.com/pqina/filepond/issues/143#issuecomment-632644041

Sadly, it cannot be found in doc.

**Comment by rikschennink** [comment]
@lokpro I've updated the docs.
