### ISSUE TITLE
Add file csv

### ISSUE THREAD

**Issue by Franz0410** [pqina/vue-filepond#115]
Hello,

I want that the filepond accept csv, in accepted-fyle-types i add ".csv, text/csv, application/csv" they accept the csv but the component report thet is not a csv, ther is an error.

![image](https://user-images.githubusercontent.com/51912494/67566273-aa08cf00-f727-11e9-82f2-f02ec4231b5b.png)

**Comment by rikschennink** [comment]
See this issue: https://github.com/pqina/filepond-plugin-file-validate-type/issues/2
