### ISSUE TITLE
Bug with FilePondPluginImageTransform 

### ISSUE THREAD

**Issue by CMorrier** [pqina/vue-filepond#118]
### Summary
If the FilePondPluginImageTransform plugin is loaded in the Vue project, it is applied to all the filepond components, even if it's is unused.
If a file who is not an image is upload, an error is thrown.

### How to reproduce
https://codesandbox.io/s/vue-filepond-live-demo-qgdpy
Try to upload a PDF or another file who is not an image.

There is 2 components : 
- FilePondWithTransform.vue who register the FilePondPluginImageTransform plugin
- FilePondNoTransform.vue who does not register the plugin

Only the second is used, but an image is expected by filepond.

![Console error](https://user-images.githubusercontent.com/56883838/70242305-e5f47280-1770-11ea-8bbe-4a46ae5e2be2.png)

### Expected behaviour
If the plugin FilePondPluginImageTransform  is not registered, it should not expect to upload an image.

### Additional information
I tried different registration method and properties but have no solution beside async loading the components, and the problem still appear as soon as the component with FilePondPluginImageTransform is imported.

Thank you for your help and congratulations for the wonderful packages.

| Environment  | Version
|------------- | -----------
| OS           | Windows 7
| Device       | Desktop
| Browser      | Firefox dev / Chrome

**Comment by rikschennink** [comment]
Plugins are registered internally and are available to all instances. You can set the `allowImageTransform` prop to `false` on a specific instance to disable it.

**Comment by CMorrier** [comment]
I already tried this, the problem is still present.

Here is the snippet updated with the prop : https://codesandbox.io/s/vue-filepond-live-demo-gsl3o

**Comment by rikschennink** [comment]
@CMorrier It turns out this was a bug in the transform plugin, just published version `3.6.1` it should fix this.

**Comment by CMorrier** [comment]
Problem solved with `3.6.1` thank you very much.
