### ISSUE TITLE
v-on:updatefiles fires twice

### ISSUE THREAD

**Issue by kiwo12345** [pqina/vue-filepond#119]
If I add the `v-on:updatefiles` method I can see that it fires twice every time a file is added. It only fires once if a file is removed.

### How to reproduce
Add `v-on:updatefiles="handleFilePondUpdateFile"`

```
handleFilePondUpdateFile(files){
     console.log("Test")
}

```

### Expected behaviour
Fire once

**Comment by rikschennink** [comment]
There's an update to one of the files inside the array, it currently fires multiple times to keep track of all these changes.

**Comment by rikschennink** [comment]
closed because inactive
