### ISSUE TITLE
Error installing filepond on Docker

### ISSUE THREAD

**Issue by PauloViniciusBaleeiro** [pqina/vue-filepond#120]
I´m getting error when installing filepond from package.json on Docker(version 19.03.5-rc1). On the package, I updated filepond version to 4.8.2 and now, on npm install step on docker, I´m getting the error below:
 
npm WARN tarball tarball data for filepond@4.8.2 (sha512-JTSvxTQGbCXMZGoPOIjCKImv+Al3Y5z3f6gRoUGlQdqpnMHdnwOV0WG3hRCVBDN64ctAN3pgKtofkWfsnwwoTA==) seems to be corrupted. Trying one more time.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-12T12_19_55_196Z-debug.log

### Additional information
I didn't find the mentioned log.

| Environment  | Version
|--------------- | -----------
| OS                 | Linux Fedora Server 29 
| Docker          |  version 19.03.5-rc1, build 3e40132

**Comment by rikschennink** [comment]
Weird. I just ran a quick install to test and it works as intended
![Screenshot 2019-12-12 at 13 45 54](https://user-images.githubusercontent.com/1132575/70713212-c9fb4e80-1ce5-11ea-8197-30ef61b72eb8.png)
.

**Comment by PauloViniciusBaleeiro** [comment]
I'll close, sorry about yout time. I updated the package.json manually and the package-lock.json file was wrong(manually).
Thnak you.
