### ISSUE TITLE
$attrs/$listeners is readonly

### ISSUE THREAD

**Issue by vhcraig** [pqina/vue-filepond#122]
### Summary
Using FilePond in Vue component leads to unexpected behaviour. Specifically `[Vue warn]: $attrs is readonly.` and `[Vue warn]: $listeners is readonly.` (image in additional information below). My understanding is that this is very common when different versions of Vue are used. In the project I am working on there are a number of "sub modules" or components. This is inline with Laravel Nova's structure which is very modular to allow for component sharing.

### How to reproduce
Reproduction of this issue is challenging as it requires a Laravel Nova license. I am however fairly confident that it is related to the `import Vue from 'vue'`. A similar issues existed in another repository with the exact same use case, which can be seen here: https://github.com/Agontuk/vue-cropperjs/pull/40

### Additional information
Console screenshot:
![image](https://user-images.githubusercontent.com/52801576/71558506-fdb3d380-2a5c-11ea-8abb-de786cdee391.png)

| Environment  | Version
|------------- | -----------
| OS           | Linux
| Device       | Desktop
| Browser      | Firefox and Chrome (both latest and 64bit)

**Comment by vhcraig** [comment]
I've switched it out with vanilla FilePond and can confirm the issue is related to the Vue adapter or framework.

**Comment by rikschennink** [comment]
Hi, this looks like a code format warning, maybe you can instruct the framework to ignore the FilePond adapter component?

**Comment by vhcraig** [comment]
I recognise that it is a warning and will not reflect in a production build but the error exists for a very good reason. In this instance, it is because two instances of Vue exists which would add an unnecessary amount of overhead for a file uploader.

I'm happy for you to close the issue but do not believe this adapter lives up to the standard of FilePond as a while.

I'd be open to submitting a PR if you're interested in a minor restructure?

**Comment by rikschennink** [comment]
@vhcraig I'm always interested in that.

**Comment by vhcraig** [comment]
Great, I'll leave this issue open and find some time in the next week or so.

**Comment by msencenb** [comment]
I have been running into this in one of my projects as well, which appears to be related to a double import of Vue as described by @vhcraig. 

I'm not yet confident enough in my Vue skills to understand the nuances of Components vs Plugins vs Directives and which one FilePond should be (Component as a bet I suppose). This project https://github.com/Akryum/v-tooltip/blob/master/src/index.js seems to have a clean export strategy that respects the already existing Vue instantiation.

**Comment by vhcraig** [comment]
Sorry for the delay on my PR, it's been a rough start to the year. I fully intend on assisting in resolving this issue. You're more than welcome to take a crack at it if your issue is time sensitive, otherwise I'd suggest using the vanilla JS FilePond.

The FilePond Vue adapter is fairly simple so a Component would probably make sense in this case. If you have a look at the PR linked in my initial issue it outlines exact what the issue is and how it needs to be resolved. The conversation around it can be seen here: https://github.com/Agontuk/vue-cropperjs/issues/26. The export strategy you've also provided in v-tooltip is also perfect 👌

**Comment by OzzyTheGiant** [comment]
Can confirm that this issue still exists but it's only because of a problem with multiple versions of vue being installed on my repo, so to resolve it, I had to ensure that all dependencies point to only one version of Vue, most likely the latest version. Be sure that your lock file is cleaned out of multiple Vue instances, and if for some reason it's not working, try deleting the lock file and `yarn install` to reset it.
