### ISSUE TITLE
How to reference specific child vue-filepond instance when multiple exist?

### ISSUE THREAD

**Issue by madscientistproductions** [pqina/vue-filepond#123]
Hi there,

I have a specific use case whereby I have a wrapper "upload-component" and within that, I have a number (variable) of vue-filepond components that are added depending on the number of "slots" passed in as a prop to the wrapper.

My template looks something like this:

```vue
<div v-for="slot in slots" :key="slot.displayorder">
      {{slot.title}}

    <file-pond 
        :ref="'filepond_' + slot.displayorder"
        allow-multiple="true" 
        label-idle="<span class='has-text-weight-bold'><i class='fas fa-arrow-alt-right'></i> Drop <span class='dropzone-type'></span> files</span> (or click) to upload"
        :accepted-file-types="fileTypes"
        :files="files"
        :server="serverOptions"
        @processfile="processUpload"
        />
</div>
```

The struggling point I'm having right now is that while the actual file selection and upload works as-is for multiple slots, because it only ever runs through a single processUpload method inside my wrapper component, and because the processfile only returns (error, file), it's impossible for me to know *which* sub-filepond component was used to actually upload a file with.  This is important since the UI has a table-like structure underneath each filepond with preview, file details, metadata, etc.

Is there a way that I can know which specific vue-filepond component on a page was used for which individual file upload?  Then I can assign the correct "slot" to that file.

Thanks!

**Comment by rikschennink** [comment]
Hi, you could assign a unique id and then on the processfile handler you store the unique id and the files.

**Comment by rikschennink** [comment]
closed because inactive
