### ISSUE TITLE
Module not found: Error:

### ISSUE THREAD

**Issue by Lunberg88** [pqina/vue-filepond#13]
Hi, again. I was been on vocations, so i couldn't answer on your message.

I'm trying to re-install vue-filepond, but have the same issue.

`Module not found: Error: Can't resolve 'filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.esm.js' in '/Applications/AMPPS/www/vue-admin/src/components'`

I'm using vuetify v1.0.16

**Comment by rikschennink** [comment]
Have you installed the plugin?

```bash
npm install filepond-plugin-file-validate-type --save
```

**Comment by Lunberg88** [comment]
Thanks, installed:
`
filepond-plugin-file-validate-type and filepond-plugin-image-preview
`
Now it works fine!

**Comment by rikschennink** [comment]
Fantastic!
