### ISSUE TITLE
addFile "Can't load URL"

### ISSUE THREAD

**Issue by marbuser** [pqina/vue-filepond#130]
# Summary
I'm using S3 to store my images, and as far as I'm aware filepond allows remote urls? When calling `addFile` with the URL for my "initial files" it constantly replies with an error of; 
```
error:
type: "error"
body: "Can't load URL"
code: 400
```

Which isn't very helpful when it comes to debugging. I've tried setting the option `{ type: 'local' }` but that doesn't seem to work.

### How to reproduce
This is the code I'm using;
```js
    init() {
      this.value.forEach(async (i) => {
        await this.$refs.pond.addFile(i);
      });
    }
```
### Expected behaviour
It should send the request, grab the file and convert it into a blob so that it can be displayed.

| Environment  | Version
|------------- | -----------
| OS              | macOS
| Device       | MacBook Pro
| Browser     | Chrome

**Comment by rikschennink** [comment]
Does your developer console show any errors?

**Comment by kdaghari** [comment]
I'm not OP but I'm having the same issue. As far as the dev console is concerned that's the only error it shows. Here's a more detailed look:

![screen](https://user-images.githubusercontent.com/50710559/71823944-b2bb4100-3098-11ea-8599-82add0b084db.png)

Note: have tried using the `fiels` prop, while it does not display the preview, it raises no error.
Also, have tried https://github.com/pqina/filepond/issues/44#issuecomment-554319116 but still same issue.

**Comment by rikschennink** [comment]
This is the error thrown by the browser:

**Access to XMLHttpRequest at 'https://screenrant.com/wp-content/uploads/2017/07/Rick-and-Morty.jpg' (redirected from 'http://screenrant.com/wp-content/uploads/2017/07/Rick-and-Morty.jpg') from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

Set the appropriate CORS headers on the server and you can load the image.

You can also use the FilePond `server.fetch` end-point to route the request through your own proxy server. https://pqina.nl/filepond/docs/patterns/api/server/#fetch

**Comment by yourtechnicaldeveloper** [comment]
Hi @rikschennink 
Here is my code for the  file pond add files from google cloud (public access bucket)
```
$(function(){
        // Turn input element into a pond with configuration options
        $.fn.filepond.registerPlugin(FilePondPluginFileEncode);
        $.fn.filepond.registerPlugin(FilePondPluginFileValidateType);
        images.filepond({
            allowMultiple: true,
            acceptedFileTypes: ['image/png']
        });
    
         images.filepond('addFile', "https://storage.googleapis.com/doohma_media/ads/32/banner-right-image.png?Expires=1584725451&GoogleAccessId=doohmauk-dev%40appspot.gserviceaccount.com&Signature=IaYlbUpDQ%2FPTSXxsyunT0sATeOFVPNAWm0Qlu0f6tHL1NpZCNZ3SqVMfXdamrwOv%2FSaeZxC%2FoE7%2F%2FZk0H6KeawQYxySDhcL1YQJ3hSE5ADMS%2Fzx8XpEyg90P56XoEW6glktGuV8Bbbzmqk2uTR9N3CL%2FxucIPpAiaqFr2XJSeDLkErNhRyqeuAzWvQObiOYhXmsxny3J6mQk7iNSeo44ReTtiB2NLHio0nFbWd1PQ7umDFNiTny6V8Vbob7OJvEhSNFN9oMlOVC0UsQeQOkJHhufNz%2FsyQ%2F%2FhKd6H%2BUYaheUlwpSmoNm3X0Y6xG%2F1Og94nbS9t3cOM9uR2wu9cBb1w%3D%3D").then(function(file){
                console.log('file added', file);
            });
            
```
as we can see from the screenshot that filename is correct but unable to load it see attached below if you can help in this case many thanks
![image](https://user-images.githubusercontent.com/50608000/77096327-34363480-6a35-11ea-8492-5a3033ab9d84.png)

**Comment by rikschennink** [comment]
@yourtechnicaldeveloper you probably have to configure CORS headers on your server.

**Comment by yourtechnicaldeveloper** [comment]
@rikschennink  
Thanks for the reply 
I have already enabled CORS headers on the server as well as google cloud bucket and moreover google bucket has public rea access and I am able to load these images in other javascript code any clue here? Thanks for your support.

**Comment by rikschennink** [comment]
@yourtechnicaldeveloper please don't double post. I don't have a clue, but again, this is very likely a server configuration issue. I can't help with that.

**Comment by BenHarris** [comment]
I have hit this issue today (although with AWS S3 presigned URLs). The image displays correctly if injected straight into an image tag, but when passed into the create object or with addFile, it fails with a 400 error. It looks to me like the issue is caused by filepond encoding the URL, which is already encoded.

**Comment by rikschennink** [comment]
@BenHarris Do you see any errors in your developer console.
