### ISSUE TITLE
How can I use Hooks(beforeRemoveFile) in vue app?

### ISSUE THREAD

**Issue by NikEdu8** [pqina/vue-filepond#131]
Hello fellow developer!

How can I use Hooks(beforeRemoveFile) in vue app?

**Comment by parkaran** [comment]
Hello @NikEdu8,

`<file-pond :beforeRemoveFile="beforeRemove"/>`

and in the method `beforeRemove` return `false ` to prevent removal, or return a `Promise  `and resolve with `true `or `false`

check this for more information on other hooks: https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#hooks

and this for callbacks:
https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#callbacks

**Comment by NikEdu8** [comment]
Thanks)

**Comment by gerbenqikker** [comment]
@parkaran can it be that this is not working at this moment in time? using your exact code, and it doesn't seem to get called at all. using filepond `4.29.1` and vue-filepond `6.0.3`
