### ISSUE TITLE
How to create multiple instances and multiple setOptions in Vue way?

### ISSUE THREAD

**Issue by putrapurba** [pqina/vue-filepond#135]
Hi!
How to achieve as the title said? I have tried to put `:server` on component but not work. It work when I use setOptions on script, but I can't figure out how to make multiple setOptions. I can only make it work only in vanilla JS.

**Comment by rikschennink** [comment]
There is one "global" `setOptions`, you have to pass props to the component to override these options.

This should work:

```vue
<file-pond v-bind:server="myServerConfig"/>
```
