### ISSUE TITLE
Browser Compatability

### ISSUE THREAD

**Issue by Lerudan** [pqina/vue-filepond#136]
Hi!
Since vue.js has compatability to older browsers than filepond does, is there any way to use the Filepond.supported() function with the vue component?
Or did I miss something in the docs and the vue component ads the missing support for IE 9 and IE 10? 
Thanks in advance!

**Comment by rikschennink** [comment]
Hi, You can use the supported method, but FilePond won't work on IE9 and/or IE10, in those cases the `supported` method returns `false`

**Comment by Lerudan** [comment]
Thanks for the fast answer.

Yes, I got that, but where can I find the supported method since I only have the filepond vue component instance at hand? 

```
<script>
    import vueFilePond from 'vue-filepond';
    import 'filepond/dist/filepond.min.css';

    import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size';

    const FilePond = vueFilePond(FilePondPluginFileValidateSize);
    export default {
        [...]
        methods:    {
            handleFilePondInit: function () {
                console.log(FilePond.supported());
                console.log('FilePond has initialized');
            },
           [...]
        },

    }
</script>
```

This only throws 
> [Vue warn]: Error in v-on handler: "TypeError: FilePond.supported is not a function"

to the console.
Equally, `this.$refs.pond.supported()` does not work, though this isn't really surprising.

Thanks in advance.

**Comment by rikschennink** [comment]
The `supported` method is currently not exported by the component. The component won't have a `_pond` property if supported returns false.
