### ISSUE TITLE
How can I add required validation on filepond vue?

### ISSUE THREAD

**Issue by mosestoh** [pqina/vue-filepond#138]
I read on this docs : https://github.com/pqina/vue-filepond

I try to add like this :

```vue
    <FilePond 
        allowMultiple="true"
        accepted-file-types="image/jpg, image/jpeg, application/pdf"
        maxFileSize="2MB"
        required="true"/>
```

multiple, validation file type, max file works

But, required does not works

How can I solve this problem?

**Comment by rikschennink** [comment]
I think you might have to set it as a `v-bind:required="true"` not a 100% sure.

**Comment by mosestoh** [comment]
@rikschennink It does not works

**Comment by rikschennink** [comment]
I just tested this to be sure.

```vue
<form method="post" action="">
    <file-pond v-bind:required="true"/>
    <button type="submit">submit</button>
</form>
```

![Screenshot 2020-02-17 at 08 30 31](https://user-images.githubusercontent.com/1132575/74632524-d8d80480-515f-11ea-8a4a-aa3b7f7b9854.png)
