### ISSUE TITLE
Please update the filepond dependency to solve a confirmed bug

### ISSUE THREAD

**Issue by cloydlau** [pqina/vue-filepond#145]
#87 # Summary

A confirmed filepond bug: https://github.com/pqina/filepond/issues/465
It's said to be fixed in 4.13.0.
So please update the filepond dependency to 4.13.0 to solve this problem, appreciated.

**Comment by rikschennink** [comment]
FilePond is a peer dependency, so you can run `npm i filepond@latest` to get the latest version.

**Comment by cloydlau** [comment]
My filepond dependency is already latest(4.13.0), but this bug is still reproducible. So I check the package.json of vue-filepond@6.0.2 and I found the version of filepond dependency is 4.9.3.
