### ISSUE TITLE
What is the correct way to preload files while integrating with Vuex?

### ISSUE THREAD

**Issue by Peppe87** [pqina/vue-filepond#146]
Hi! Thank you for this nice plugin. 

I'm trying to understand how preload the files in the most correct way. 

I've a dynamic component, put inside a multistep form, so everytime the user return to the step with the filepond input, it's necessary to restore the previosly saved files. 
Those files are put inside vuex, they are not uploaded until the form is definitively submitted. Thus I don't think I can rely on server api to restore them.

I hoped the plugin would automatically "bind" the existing files while using v-model, but that is not working - it actually delete the existing files in the relative Vuex variable.
 
For now I've resolved using "v-bind:files="localPrintFiles"", and on beforeMount() hook populating the "localPrintFiles" variable with the data inside the Vuex variable. 

However, I don't know if this is a reasonable approach, or if there is a better one to implement this functionality 

```vue
<template>
  <div :id="id" :class="classes">
    <file-pond
      ref="pond"
      label-idle="Rilascia qui i file o <span class='filepond--label-action'>sfoglia</span>"
      allow-multiple="true"
      accepted-file-types="image/*, application/pdf"
      v-model="printFiles"
      v-bind:files="localPrintFiles"
      :allowFileEncode="true"
      :instant-upload="false"
      :server="null"
    />
  </div>
</template>

<script>
import vueFilePond from "vue-filepond";
import FilePondPluginFileEncode from "filepond-plugin-file-encode";
import FilePondPluginFileValidateType from "filepond-plugin-file-validate-type";
import FilePondPluginImagePreview from "filepond-plugin-image-preview";
import "filepond/dist/filepond.min.css";
import "filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css";
const FilePond = vueFilePond(
  FilePondPluginFileEncode,
  FilePondPluginFileValidateType,
  FilePondPluginImagePreview
);

export default {
  components: {
    FilePond
  },
  props: {
    classes: {
      type: [String, Array]
    },
    id: {
      type: String
    }
  },
  data() {
    return {
      localPrintFiles: []
    };
  },
  beforeMount() {
    this.localPrintFiles = this.$store.getters["form/files"];
  },
  computed: {
    printFiles: {
      get() {
        return this.$store.getters["form/files"];
      },
      set(value) {
        this.$store.dispatch("form/setFiles", value);
      }
    }
  }
};
</script>
```

**Comment by rikschennink** [comment]
You could set up a custom server API that binds the files, that way you could use the `server` property, the property is called `server` but I've been wanting to rename it to `store` so you can use it to upload files to a server or store files locally or restore files from local state, it's basically a way for FilePond to send and receive files.

**Comment by Peppe87** [comment]
Thank you for the answer. 
I was indeed mislead by the name "server", so I didn't think it could be also  "local". Probably would be good to at least specify this thing in the official docs.

However, I have a doubt, after reading a bit more the docs (especially server API), some other issues and doing a bit of testing with [hello world example](https://github.com/pqina/vue-filepond/blob/d91799752946f91578d72062e06633c1223c2303/example/src/components/HelloWorld.vue).

From my test it seems it is necessary that the :files props is defined and must have some (valid) value inside, otherwise filepond won't execute load() when initialized. 

Therefore, I suppose the component should be something like this - I'm writing only the significant changes in comparison to the previous code block:

`
<template>
  <div :id="id" :class="classes">
    <file-pond
      ref="pond"
      label-idle="Rilascia qui i file o <span class='filepond--label-action'>sfoglia</span>"
      allow-multiple="true"
      accepted-file-types="image/*, application/pdf"
      :allowFileEncode="true"
      :files="localPrintFiles"
      :server="localServer"
    />
  </div>
</template>
<script>
[...]
export default {
[...]
    data: function () {
      return {
        localServer: {
          process: (fieldName, file, metadata, load) => {
            console.log("process");
            //some logic to save the file in the Vuex variable
          },
          load: (source, load) => {
            console.log("load");
           //some logic to load the files from Vuex
          },
        },
        myFiles: [
        /*
         an array of existing files similar to
          {
            source: "photo.jpeg",
            options: {
              type: "local",
            },
          },
        */
        ],
      };
    },
};
</script>
`


But now I don't understand what would be the benefit of this implementation over the one I've already using v-model? 
Is the approach I've used somehow bad, or implementing the "server" would just allow to use the api related to? (which as far I can see for now, I don't need for this specific project).

**Comment by rikschennink** [comment]
I think both approaches are fine, there's at this point no real "one solution" I could advise

**Comment by Peppe87** [comment]
Ok, I see. Thank you for the assistance. 
Then for this project I'll continue using  "my" approach using v-model - as it works and it's already coded.
