### ISSUE TITLE
Type check failed for prop "labelFileProcessingError"

### ISSUE THREAD

**Issue by Etheryte** [pqina/vue-filepond#150]
### Summary

As covered [here](https://github.com/pqina/filepond/issues/229#issuecomment-463110194), `labelFileProcessingError` can be either a string or a function.  
Functionally this works, however, the Vue prop types incorrectly warn in development mode:

> [Vue warn]: Invalid prop: type check failed for prop "labelFileProcessingError". Expected String, String, got Function 

### How to reproduce

Set `labelFileProcessingError` as a function:

```ts
const filePondOptions = {
  labelFileProcessingError: function() {
    return "Fancy error";
  },
};
```

Note the above warning is logged when running in **development** mode. (Vue doesn't log these warnings in production by default.)

### Expected behaviour

The code already works correctly functionally, however the prop types are incorrectly configured for Vue.  
The expected behavior would be to have no warning logged as this is a valid configuration.

**Comment by rikschennink** [comment]
@Etheryte Happy to accept a PR

**Comment by SinBirb** [comment]
Hi, we still get this error when using vue-filepond like this:

```html
<file-pond
      ref="pond"
      name="file"
      :label-file-processing-error="fileUploadErrorLabelHandler"
>
```

`fileUploadErrorLabelHandler` is declared in Vue as a function in `methods` like this:

```ts
methods: {
  fileUploadErrorLabelHandler(error: any): string {
    return "foo";
  }
}
```

Observed and expected behavior from original post still apply.

**Comment by rikschennink** [comment]
@SinBirb It is defined in the types file:

`labelFileProcessingError?: ((error: any) => string) | string;`

Is this with the latest version of FilePond?

**Comment by firojghimire-sk** [comment]
Still getting this warning with filepond 4.28.2

**Comment by rikschennink** [comment]
I don't know enough of Vue and TypeScript to address this, will re-open.

**Comment by masterkain** [comment]
getting the same

![Screenshot 2021-09-07 at 11 16 02](https://user-images.githubusercontent.com/12844/132319075-13a7db24-4622-4722-a4e4-c556223068dc.png)

**Comment by Libertie** [comment]
The source of this issue is line 80-84 of `dist/vue-filepond.js`:
```
    props[prop] = {
        type: [String, getNativeConstructorFromType(_filepond.OptionTypes[prop])],
        // set this default value so we know which props have been explicitely set by user on component
        default: "__unset__"
      };
```
pqina/vue-filepond is deriving the prop type by examining `OptionTypes` from [pqina/filepond](https://github.com/pqina/filepond/).

The issue can be resolved by manually adding `Function` as a valid prop type (tho it would need to be conditional to avoid impacting all the other props). Or presumably it could be resolved by modifying the equivalent property in pqina/filepond.
