### ISSUE TITLE
DELETE request has empty object as body

### ISSUE THREAD

**Issue by rugni** [pqina/vue-filepond#151]
### Summary

I've set my filepond server on my file pond template like:
`server="http://localhost:3000/imageUpload"`

When I upload the image, I return an id (here 1234) as described in the docs.
This Id is stored in my filepond file object as expected: 

`{getMetadata: ƒ, setMetadata: ƒ, abortLoad: ƒ, abortProcessing: ƒ, …}
id: "8x1cmi9da"
origin: 1
serverId: "1234"
...`

So far all good.

I can also click the revert button and the DELETE request is arriving at my server as expected. 
My problem is, that the request comes with an empty object as body. But I expect the delete request to send my server id.

### How to reproduce

I'm using the vue-filepond object with the following plug-ins:
`const filePond = vueFilePond(FilePondPluginImageExifOrientation, FilePondPluginFileValidateType, FilePondPluginImageResize, FilePondPluginImageTransform, FilePondPluginImagePreview)`
and I'm using the image resize plugin to store three files with different resolution at the same time

I've setup a custom node.js backend server that handles the requests:

`router.delete('/imageUpload', (req, res) => console.log(req.body))`

this logs: `Object {}` from my revert request

### Expected behaviour

I expect the body to contain the id, 1234

Any ideas? Thank you!

| Environment  | Version
|------------- | -----------
| OS               | MacOS 
| Browser      | Chromium

**Comment by rikschennink** [comment]
Hi, can you see the body of the request in the browser dev tools network tab?

**Comment by rugni** [comment]
### Solved
Yes, I can see the request in the browser dev tools.
I figured out that the issue was in the backend:

The delete request is sending the body as plain text. I'm using the express middleware body-parser to get the body of requests. It was configured to only parse request payloads that are json objects:

`app.use(bodyParser.json());`

by adding the following Line, the body is accessible as wished. 

`app.use(bodyParser.text());`

Now `router.delete('/imageUpload', (req, res) => console.log(req.body))` prints my Id

Thank you for your help!
