### ISSUE TITLE
use Doka beside file-pond

### ISSUE THREAD

**Issue by falahatiali** [pqina/vue-filepond#153]
How can I use Doka with filepond  in development? 
is there any ways for using  it as free?

**Comment by rikschennink** [comment]
Hi, [Doka](https://pqina.nl/doka/) is only available in the commercial package itself, so you need to purchase the product before you can add it. There’s a 60 day money back guarantee to cover any disappointments.

**Comment by falahatiali** [comment]
@rikschennink yeah it's a little expensive :)

**Comment by rikschennink** [comment]
Fully understand, the price will not match every use case but for companies it’s very fair (compare to developer hourly rate).
