### ISSUE TITLE
Really bad documentation and very buggy but great script

### ISSUE THREAD

**Issue by gdinko** [pqina/vue-filepond#155]
Hello fellow developer!

💡 If you want to submit a feature request, go right ahead!

🐜 If you've found a bug, please use the template below to report it.

**The more details you provide, the more inclined other developers are to help you and the faster the problem is resolved.**

If you think the issue is related FilePond itself and not the Vue framework or adapter, please submit the issue in the FilePond repository.

Please format code snippets using backticks and don't forget to set the appropriate language.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

### Summary
MetaData Bugs

laravel

app.js
import vueFilePond from 'vue-filepond';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.esm.js';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.esm.js';
import 'filepond/dist/filepond.min.css';
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css';
import FilePondPluginFileMetadata from 'filepond-plugin-file-metadata/dist/filepond-plugin-file-metadata.esm.js';

vue component:

allowFileMetadata="true"
data-file-metadata-hello="world"

result -> not working

========

bug 2:

allowFileMetadata="true"
v-on:addfile="handleFilePondAddFile"

working , but metadata has the same name as the file, not good idea

in laravel is the same:

print_r($request->file('model_images'));
        print_r($request->model_images);

========

extra bug:

there is some color var in the metadata, maybe test?

<img width="1011" alt="Screenshot 2020-05-26 at 0 14 42" src="https://user-images.githubusercontent.com/2735905/82843511-07dfde00-9ee6-11ea-8702-4455c917fc8f.png">
<img width="448" alt="Screenshot 2020-05-26 at 0 14 55" src="https://user-images.githubusercontent.com/2735905/82843513-0adace80-9ee6-11ea-8479-064c441c490a.png">
<img width="453" alt="Screenshot 2020-05-26 at 0 15 04" src="https://user-images.githubusercontent.com/2735905/82843514-0b736500-9ee6-11ea-9a9d-d098a7fd4c30.png">
<img width="731" alt="Screenshot 2020-05-26 at 0 15 28" src="https://user-images.githubusercontent.com/2735905/82843515-0b736500-9ee6-11ea-8fd9-644da59f0cc1.png">

**Comment by rikschennink** [comment]
Closed because insufficient details and doesn’t follow issue template.
