### ISSUE TITLE
Export all types 

### ISSUE THREAD

**Issue by Kurbezz** [pqina/vue-filepond#158]
When use vue-filepond with typescript can't define type of callbacks, server option and etc.

Export all types for better types checking with typescript.

Example:

```
<template>
  <filepond :server="{ process }">
  </filepond>
</template>

<script lang="ts">
import { ActualFileObject, ProgressServerConfigFunction  } from 'filepond'; // not exported
export default class Uploader extends Vue {
  process(fieldName: string, file: ActualFileObject, metadata: { [key: string]: any }, load: (p: string | { [key: string]: any }) => void, error: (errorText: string) => void, progress: ProgressServerConfigFunction, abort: () => void) {}
}
</script>
```
or can't do
```
<template>
  <filepond :server="{ process }">
  </filepond>
</template>

<script lang="ts">
import { ProcessServerConfigFunction } from 'filepond'; // not exported
export default class Uploader extends Vue {
  process: ProcessServerConfigFunction = (fileName, file, metadata, ...) => { }  // With declared arguments types
}
</script>
```

**Comment by Kurbezz** [comment]
@rikschennink Is doesn't vue-filepond problem. It is can't import filepond types for export too.

**Comment by rikschennink** [comment]
Maybe importing them by referencing the types file works?

```js
import { ProcessServerConfigFunction } from 'filepond/types/index.d.ts'
```

**Comment by Kurbezz** [comment]
![image](https://user-images.githubusercontent.com/14016995/85952285-c0c78b80-b970-11ea-9648-eda638bc415c.png)

**Comment by rikschennink** [comment]
Looks like you're still importing from `'filepond'`?

**Comment by Kurbezz** [comment]
> Looks like you're still importing from `'filepond'`?

![image](https://user-images.githubusercontent.com/14016995/85954672-e14c1180-b981-11ea-89d8-49b04940cc03.png)
