### ISSUE TITLE
Is it possible to have per file methods after upload?

### ISSUE THREAD

**Issue by Pitu** [pqina/vue-filepond#16]
First of all, thanks for such a silky smooth file upload, it's great!

After finding filepond I started a little migration process from what I had to filepond, but I'm facing a challenge right now. In my case, when a file is successfully uploaded I return an object from the API that contains a full url to that file the user just uploaded. So is there any way to read that response and be able to add a new event to the file element? Ideally I'd like people to be able to click on the successfully uploaded a file and open a new tab to access it.

Would this be possible in filepond's current state of development?

**Comment by rikschennink** [comment]
@Pitu Aw thanks, glad to hear that :D

The most recent version of filepond adds an `onload` method to the `process` property of the `server` [configuration](https://pqina.nl/filepond/docs/patterns/api/server/#configuration). This allows parsing the server response and selecting the property/value you want to use as the unique file identifier ( stored in the file item `serverId` property ). I think this is exactly what you need.

You can then listen to the `processfile` event and get the `serverId` from the file item when the file has been processed successfully. 

There's currently no way to click the items to do something with them or add custom buttons. You could listen for clicks on the filepond element and then determine which element was clicked ( by using the event `target` property ) then you could get the matching `serverId` as it's also stored in a hidden input element within each file item.

**Comment by Pitu** [comment]
Awesome! This helps greatly. Thank you!
