### ISSUE TITLE
"filepond" input not posting as an array with multiple file upload

### ISSUE THREAD

**Issue by pixeldemon9** [pqina/vue-filepond#165]
After uploading multiple files, a unique ID is returned for each file.  However, the html created for the inputs does not create an array, so only the last "filepond" input is submitted.

```
<fieldset class="filepond--data">
<input type="hidden" name="filepond" value="44c755f8-128b-488b-87a4-af9574a9f840">
<input type="hidden" name="filepond" value="582a86f-2191-4c4b-b593-8d022c9a3b12">
<input type="hidden" name="filepond" value="14f6ecff-9121-4812-a3fa-ed4032660f48">
</fieldset>
```

**Expected behavior**
The input names should be created to submit as an array:
`name="filepond[]"`

**other details**

The filepond tag I am using:

`<file-pond 
            allow-multiple="true"
            max-files="3"
            allowImagePreview="false"
            server="/upload"
/>`

**Comment by rikschennink** [comment]
You can change the name using the `name` prop.

```jsx
<file-pond name="filepond[]" />
```

**Comment by pixeldemon9** [comment]
@rikschennink Thank you, that works.  I think it would make more sense to submit the individual upload requests in a non-array field, and upload the form as an array, but this will do.
