### ISSUE TITLE
Support for Vue3

### ISSUE THREAD

**Issue by adarshmadrecha** [pqina/vue-filepond#169]
**Is your feature request related to a problem? Please describe.**
Update filepond for vue 3

**Describe the solution you'd like**
Make it compatible with Vue 3

**Describe alternatives you've considered**
NONE

**Additional context**

**Comment by TomSinclair** [comment]
Any plans to support Vue 3?

**Comment by rikschennink** [comment]
Yes, just very very busy

**Comment by camiant** [comment]
any news? 😊🤞

**Comment by rikschennink** [comment]
I’m having to use FilePond in a Vue 3 project do it should be there soonish.

**Comment by rikschennink** [comment]
Done, see v7.0.0

**Comment by stafyniaksacha** [comment]
Hi @rikschennink 
I have made this based on your plugin, I use it on vue3 and vite2

https://gist.github.com/stafyniaksacha/d37d55b9a972a5b3e2012082d587ca3f

**Comment by rikschennink** [comment]
@stafyniaksacha I just published v3, we posted at the same time. :)
