### ISSUE TITLE
Can't load vue-filepond via SystemJS

### ISSUE THREAD

**Issue by novikov-alexander** [pqina/vue-filepond#17]
I tried to load .js and .esm.js files.

In the 1st case I have an error "exports is not defined"
In the 2nd case I have an error "Unable to dynamically transpile ES module.  A loader plugin needs to be configured via `SystemJS.config"

**Comment by rikschennink** [comment]
Hi @novikov-alexander! Unfortunately, I'm not very familiar with SystemJS, I did search around a bit and this sounds very similar to this issue on the Vue repo, can you check if that solves the problem?
https://github.com/vuejs/vue/issues/6815

**Comment by novikov-alexander** [comment]
Hi @rikschennink! 
Unfortunately, I use right config for TypeScript compiler. Now I'm trying to recompile vue-filepond via babeljs with umd plugin.

**Comment by rikschennink** [comment]
@novikov-alexander I'll await your results.

**Comment by novikov-alexander** [comment]
@rikschennink I did that I promised. Also I've added this string manually to the beginning of the file
`        define("vue-filepond",['exports', 'vue', 'filepond'], factory);
`
because initial string after compilation was 
`
        define(['exports', 'vue', 'filepond'], factory);
`

It works for me but I'm really bad in JS modules to make correct pull request.

**Comment by rikschennink** [comment]
@novikov-alexander I did a quick search, it seems that this might be a configuration issue outside of SystemJS (gulp?).
https://github.com/systemjs/systemjs/issues/995

[Anonymous modules are preferred over named modules](https://stackoverflow.com/questions/19720646/named-module-vs-unnamed-module-in-requirejs) so I prefer to leave out the name.

**Comment by novikov-alexander** [comment]
I've moved to NodeJS + WebPack and the problem is gone away :-D
