### ISSUE TITLE
Why requestTick starts to tick even just import without using?

### ISSUE THREAD

**Issue by lustan3216** [pqina/vue-filepond#175]
![image](https://user-images.githubusercontent.com/12712127/94552478-86c89700-0289-11eb-8339-faa3d0ad16ea.png)

```
import vueFilePond from 'vue-filepond'
{
  name: 'Uploader',
  components: {
    FilePond
  }

}

<uploader v-if="false">
```

Even `v-if` keep false, it still ticks. I even don't init it.
Is that possible to start it only when using it?

**Comment by rikschennink** [comment]
The FilePond internal draw loop starts when the FilePond src file is loaded. 

See core issue here:
https://github.com/pqina/filepond/issues/243

I'm aware that it's not ideal but with 6x CPU slowdown on a MacBook from mid 2014 (with FilePond not loaded) this `requestAnimationFrame` call takes approximately `.15ms` which shouldn't be an issue, rest assured that I like to fix this but am currently looking for time to do so.

Will close, please if you have any questions, use the other issue.
