### ISSUE TITLE
Image preview with horizontal image goes outside of the preview box with grid layout

### ISSUE THREAD

**Issue by yashcodezeros** [pqina/vue-filepond#177]
**Describe the bug**
Image preview with horizontal image goes outside of the preview box with grid layout

**To Reproduce**
[https://codesandbox.io/s/vue-filepond-live-demo-forked-u54td](https://codesandbox.io/s/vue-filepond-live-demo-forked-u54td)

Upload one vertical and one horizontal image.

<img width="546" alt="Screenshot 2020-10-21 at 9 55 30 PM" src="https://user-images.githubusercontent.com/67893745/96749210-263ffc00-13e8-11eb-877a-e75690d10d20.png">

**Expected behavior**
The image should be displayed inside the preview section.

**Information about your project:**
- Your browser and the version:  Chrome 52.1
- Your operating system: MacOS 10

**Comment by rikschennink** [comment]
See note below grid entry in style docs
https://pqina.nl/filepond/docs/patterns/api/style/#grid-layout
