### ISSUE TITLE
Undefined trying to access to serverId on addfile event

### ISSUE THREAD

**Issue by LTroya** [pqina/vue-filepond#180]
**Describe the bug**
I got undefined when I tried to access the serverId when `@addfile` event is called. Even if I see it on the console

<img width="619" alt="Screen Shot 2020-11-14 at 1 43 54 AM" src="https://user-images.githubusercontent.com/6491259/99141599-e7821800-261a-11eb-8ff6-0b62d9a93d98.png">

Null values are the thing I have tried to access the value:

```
console.log('File', file, file.serverId, serverId, JSON.stringify(file));
```

**Expected behavior**

Get the `serverId` when I file is added

**Information about your project:**
- MacOSX Catalina
- Chrome 86
- Vue 2.5
- Filepond 4.9.4
- Vue Filepond 6.0.2

**Additional context**

This is my current component:

```
<file-pond
                accepted-file-types="image/*"
                allow-multiple="true"
                class-name="filepond-uploader"
                label-idle="Drag and drop your files here"
                name="file"
                ref="pond"
                server="/filepond/api/process"
                @addfile="onFileAdded"
        />
```

My method:

```
onFileAdded(err, file) {
                if (err) return;
                const {serverId} = file;
                console.log('File', file, file.serverId, serverId, JSON.stringify(file));
                
                this.$store.default.dispatch('newTask/fileAdded', {attribute: this.attribute, serverId: file.serverId});
            },
```

The result of the console is on the first screenshot. I really appreciate any help.

**Comment by rikschennink** [comment]
`onaddfile` is called when the file is added to the list, you need to subscribe to `onprocessfile` I think.

**Comment by LTroya** [comment]
@rikschennink Thanks for the answer. I use it and it works like a charm!

Any hint about why is not working `onaddfile` event? I tried so many ways to access `serverId` but no luck.

I am closing this for now.

**Comment by rikschennink** [comment]
@LTroya adfile is called when the file is added to FilePond not when it’s uploaded, so the server is isn’t known yet. when you expand the object in console it has been updated with the serverId, when console logging you’re looking at a reference to an object not a snapshot.

**Comment by LTroya** [comment]
Oh, thanks for the explanation!
