### ISSUE TITLE
preview 3d-model using file-pond

### ISSUE THREAD

**Issue by shubhamsoni8769** [pqina/vue-filepond#185]
Hi ,
I am using **Three.js** for my Project and want to preview 3d-model using File-Pond lib (same as Image preview)
Is There any way?.

**Comment by rikschennink** [comment]
I’d try to duplicate the image preview or post plugin and then rewrite it so it can render a tiny three js preview? Maybe you can create a three js instance in each preview but I’m afraid you might run out of WebGL contexts.
