### ISSUE TITLE
Multiple file transfer stops using Drag and Drop operation

### ISSUE THREAD

**Issue by sosoriov** [pqina/vue-filepond#19]
I have implemented filepond component with the server option included. In my case i need to allow the user to upload multiple files, If i use the browse file system everything works as it should but if i use the drag and drop operation the plugin only transfer 1 file and then stops.

see below:
https://www.screencast.com/t/NUt3NgZr

**Comment by sosoriov** [comment]
mmm aparently sometimes it also fails with the browse option :cry:

**Comment by rikschennink** [comment]
@sosoriov This sounds very similar to this issue: https://github.com/pqina/vue-filepond/issues/15

I had not updated the filepond dependency version, just updated it to the newest version `1.6.0`, should fix the issue.

**Comment by sosoriov** [comment]
@rikschennink damn it! still not working :S

**Comment by rikschennink** [comment]
Do you have a public test case? Happy to take a look.

**Comment by sosoriov** [comment]
@rikschennink  I found out that my backend was blocking the reponse for some reason. I made some changes in my code and now it's working

**Comment by rikschennink** [comment]
@sosoriov Aha! Glad to hear that was the problem, thanks for letting me know!
