### ISSUE TITLE
Cannot get events nor set options

### ISSUE THREAD

**Issue by weislanes** [pqina/vue-filepond#2]
Hi, this looks great but with few examples I'm left to try the intuitive approach but it's not working.

The instructions say events can be passed in and use 'init' as an example. In Filepond's docs this event is called 'oninit'. So I tried both variations for the rest of the event ('onaddfile' and 'addfile') and nothing happens. 

```html
<FilePond
            name="test"
            labelIdle="Drop an image or click to select..."
            allow-multiple="false"
            set-options="objOptions"
            accept="image/png, image/jpeg, image/gif"
            data-max-file-size="5MB"
            :init="handleFilePondInit"
            :onprocessfilestart="fileEvent"
            :onaddfile="fileEvent"
            :warning="fileEvent"
            :error="fileEvent"
            />
```

Furthermore the setOptions obj isn't doing a thing, nor is the 'accept' list (I've added the filetype plugin). 

Thanks for making this but one assumes there are props for all events/methods in the Filepond docs. If so, how to make them work? If not, can we document how to set options and trigger these other events please?

**Comment by rikschennink** [comment]
Hi, sorry that it's a bit confusing.

The events should bind correctly when using the default Vue syntax like this `@init` and `@addfile`. All other properties are available as bindable attributes `allowMultiple` instead of `allow-multiple` (I just noticed the typo in the code sample) and `acceptedFileTypes` instead of `accept`.

I'll improve the docs right away!

**Comment by rikschennink** [comment]
@weislanes Just published version `1.0.2`, it fixes a problem where plugin properties were not scooped up in time. Will close for now.

**Comment by weislanes** [comment]
Hey @rikschennink, thanks.  Actually some of the mistakes were in my code so apologies for that! 

Events are working as they should. I still can't get the accepted filetypes to work (below is as an array but also tried without) nor the maxFileSize. Also, is there a way to access the Filepond instance? 

New code:

```html
<FilePond
            name="test"
            labelIdle="Drop an image or click to select..."
            :allowMultiple="false"
            acceptedFileTypes="['image/png', 'image/jpeg', 'image/gif']"
            maxFileSize="1MB"
            @processfilestart="fileProcess"
            @addfile="fileAdded"
            @warning="fileWarning"
            @error="fileError"
            @init="handleFilePondInit"
    />
```

Note: just saw you closed this, maybe the latest version fixes what I mention here.

**Comment by rikschennink** [comment]
@weislanes Yeah, should fix it ( will of course re-open if it doesn't ).

You can pass `accetedFileTypes` like this `acceptedFileTypes="image/png, image/jpeg, image/gif"`

Can you submit a new issue for the file pond instance? That way things stay nicely ordered by question :-)
