### ISSUE TITLE
Get error message on file-pond handler [vue.js]

### ISSUE THREAD

**Issue by AMontagu** [pqina/vue-filepond#20]
Hello !

Thanks for the amazing library !

I wonder how to get the error response send by the server on filepond.

```html
<!-- template -->
<file-pond
	name="app"
	ref="pond"
	label-idle="Drop files here..."
	allow-multiple="false"
	accepted-file-types="application/zip"
	:server="serverOptions"
	:files="myFiles"
	@init="handleFilePondInit"
	@error="handleFilePondError"/>
```

```js
// script -> methods
handleFilePondError(error, file, status){
	console.log("FilePond Error: ", error, file, status);
}
```

Send everything good to a node express server with multer but I have some custom check that return errors. like this:

```js
return res.status(400).json({
	name: "CustomError",
	message: "This is my custom error"
})
```

But on the console print for error variable is : 

```js
{type: "error", code: 400, body: "Bad Request", headers: undefined}
```

And status is only the displayed text that we can configure.

So how can I get my custom response ?

PS: Dont know if filepond use it's own AJAX library or use $http by default in vue plugin but I use [axios library](https://github.com/axios/axios) so the response data is not on response.body but on response.data

**Comment by rikschennink** [comment]
Hi @AMontagu can you also post your `serverOptions`, I'm looking to see if this can be solved with the current way FilePond is set up or if I need to add additional configuration options.

**Comment by AMontagu** [comment]
Hi @rikschennink 

my serverOptions: 

```
serverOptions: {
	process: {
		url: '/api/apps/add',
		method: 'POST',
		withCredentials: false,
		headers: {
			'x-access-token': <token>,
			'csrf-token': <CSRF-TOKEN'>
		},
		timeout: 7000,
		onload: this.onLoadFile
	}
},
```

onLoadFile methods only print in console so nothing important inside

**Comment by rikschennink** [comment]
@AMontagu I just published version `1.7.0` of FilePond and added the `onerror` callback, you can use it to parse a server error response and select the value you need in the `body`.

I think this should do it:

```js
process: {
        url: '/api/apps/add',
        method: 'POST',
        onload: this.onLoadFile,
        onerror: (res) => {
            return JSON.parse(res).data
        }
}
```

**Comment by AMontagu** [comment]
Thank you @rikschennink. It's working ! 

Just an idea of improvement: Can you send to filePondError callback an error like this:
```
{type: "error", code: 400, body: "Bad Request", data: "", headers: undefined}
```

Where data field is by default `res` and that we can update with `onerror` callback  return value ?

**Comment by rikschennink** [comment]
@AMontagu Might be a good idea. I'm going to look into it. Will close this for now as the original issue has been resolved.
