### ISSUE TITLE
Browser usage example in README doesn't work

### ISSUE THREAD

**Issue by ValerianGonnot** [pqina/vue-filepond#200]
**Describe the bug**
When executing the "Usage in the browser" part of the README in a standalone HTML file, I get a bunch of errors in the console, and no filepound is displayed.

Moreover, Vue 2 is downloaded from CDN with vue-filepond 7.0.0 which handles Vue 3. 

**Expected behavior**
README examples should directly work. 

**Information about your project:**
- Your browser and the version: Chrome 89, Firefox 87
- Your operating system: Ubuntu 20.04
- FilePond version: 7.0.0

**Additional context**
Maybe I misunderstood some part of the installation or configuration as I am a beginner in web development.

**Comment by rikschennink** [comment]
Add `@6` to the cdn url to get version 6 of the plugin which works with Vue 2

```html
<script src="https://unpkg.com/vue-filepond@6"></script>
```

**Comment by izshreyansh** [comment]
Wow this worked.

https://codesandbox.io/s/filepond-o1c6z

This should be updated in the docs.

**Comment by izshreyansh** [comment]
@ValerianGonnot Let's close this issue?
