### ISSUE TITLE
Filepond not using filename in Content-disposition

### ISSUE THREAD

**Issue by ThomasWestrelin** [pqina/vue-filepond#201]
**Describe the bug**
When the event "load" is called to restore uploaded server files, the filename is not used.

![image](https://user-images.githubusercontent.com/28868131/114671043-f07b3080-9d03-11eb-9351-1f83359d294b.png)

It used the source of the filepond object.

![image](https://user-images.githubusercontent.com/28868131/114671256-2ddfbe00-9d04-11eb-9886-2f288c75a894.png)

You can see that I use Content-disposition specified in documentation.

Server-side (PHP - Laravel)
```php
// http://localhost:8080/api/filepond/load/{uniqid}
public function load(String $uniqid) {
        $file = File::where('uniqid', $uniqid)->first();
        return Storage::cloud()->response($file->path, $file->name);
}
```

Files Array of objects return by the server at init of the component.

```javascript
[{
    "source": "cXMx7cCoR",
    "options":
        {
             "type": "local"
        }
}]
```

FileComponent.vue

```javascript
<template>
    <file-pond :files="files" :label-idle="label" :server="server" :allow-multiple="allowMultiple" :credits="null" allowRevert="false"></file-pond>
</template>

<script>
export default {
    props: {
        label: {
            type: String,
            default: 'Déposer vos fichiers ...'
        },
        allowMultiple: {
            type: Boolean,
            default: false
        },
        model: {
            type: String,
            default: ''
        },
        element: {
            type: String,
            default: '',
        },
        modelId: {
            type: Number,
            default: '',
        },
        files: {
            type: Array,
            default: []
        }
    },
    data() {
        return {
            server: {
                url: '/api/filepond/',
                process: {
                    url: 'process',
                    method: 'POST',
                    ondata: (formData) => {
                        formData.append('model', this.model);
                        formData.append('element', this.element);
                        formData.append('modelId', this.modelId);
                        return formData;
                    }
                },
                revert: null,
                restore: null,
                fetch: null,
                load: 'load/',
                remove: (source, load, error) => {
                    axios({
                        method: 'DELETE',
                        url: `/api/filepond/remove/${source}`,
                        data: {
                            model: this.model,
                            element: this.element,
                            modelId: this.modelId,
                        }
                    }).then(response => {
                        load();
                    }).catch(error => {
                        error();
                    });
                },
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            }
        };
    },
}
</script>
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/28868131/114671060-f6711180-9d03-11eb-9d30-709baec39757.png)
I expect to see "base.png".

**Information about the project:**
- Browser : Chrome 89.0.4389.128
- vue-filepond : 7.0.0
- filepond : 4.27.0
- Server-side : PHP 7.4.14 - Laravel 8.24.0

**Comment by rikschennink** [comment]
Can you add quotes around the filename.

**Comment by ThomasWestrelin** [comment]
I've added quotes and It works well. Thank you.

It seems to be a problem on Laravel with the function `response()`.

```php
public function load(String $uniqid) {
        $file = File::where('uniqid', $uniqid)->first();
        return response(Storage::cloud()->get($file->path), 200)
            ->header('Content-Type', 'image/png')
            ->header('Content-Disposition', 'inline; filename="' . $file->name . '"')
            ->header('Content-Length', $file->length);
}
```

**Comment by Zack-Strife** [comment]
Sorry to re-open this but I'm having a very similar problem.

Loading the file with the load function, calling an url that respond with the file and the content disposition inline and the filename.
I can download the file and the name will be correct, but the filepond element does not show the filename.
Instead of getting "dummy.pdf" it shows "undefined"
![image](https://user-images.githubusercontent.com/16171988/149123660-30e94e5e-f763-4873-b9bf-656a635e17b8.png)

I've tried the solution provided instead of the default content disposition from Symfony, in order to add the quotes:
![image](https://user-images.githubusercontent.com/16171988/149123574-7e74d634-3eb8-404a-ac15-ced3147ddf7f.png)
But it's exactly the same

vue-filepond : 6.0.3
filepond : 4.30.3

Is it broken in version 6 or am I having another bug here ?

**Comment by rikschennink** [comment]
@Zack-Strife what does your FilePond `server` property look like?

**Comment by Zack-Strife** [comment]
```
data: function () {
    return {
      fileLoaded: false,
      myFiles: [],
      server: {
        url: '/api/upload-sf/filepond',
        process: '/post',
        load: '/get/',
        revert: './revert',
        restore: './restore/',
      }
    }
  },
```

Also I noticed that the file name is actually correctly get by the component somewhere since the <legend> tag here is filled with it: 
![image](https://user-images.githubusercontent.com/16171988/149128794-c72ae964-3d98-42e7-b480-dc1bc51d9725.png)
But that still shows Undefined on the component

**Comment by rikschennink** [comment]
Might be relevant:
https://github.com/pqina/filepond/issues/315
https://github.com/pqina/react-filepond/issues/122
https://github.com/pqina/filepond/issues/596

**Comment by Zack-Strife** [comment]
Thanks, managed to find out that it comes from the filepond-plugin-get-file thanks to those 👍 

For anyone else with the same problem, there's already an issue over there with an open PR: 
https://github.com/nielsboogaard/filepond-plugin-get-file/issues/6
