### ISSUE TITLE
Filepond on iOS only open camera

### ISSUE THREAD

**Issue by rrrrando** [pqina/vue-filepond#206]
For some odd reason when i want to use ios device to upload images the device goes straight to camera and doesn't give me the option to choose "Browse" or "Photos". But it works just fine on the filepond website. What am i missing?

**Comment by rrrrando** [comment]
Ok got it fixed, seems like `__unset__` value of `capture-method` gets passed on to the input and because of that the field defaults to environment and open the camera. Happens with Vue3/Vite. I'll close this and fiddle with it a little and create a PR if i can.

**Comment by dorinoltean** [comment]
I use `vue-filepond@7.0.0`  and got the same problem on Android Chrome. 

setting `:captureMethod="null"`  on <file-pond> did not rander the html `capture` attribute anymore.
