### ISSUE TITLE
Can't get Status enum values from vue component

### ISSUE THREAD

**Issue by kikky7** [pqina/vue-filepond#209]
**Describe the bug**
From documentation: use the FilePond.Status enum to determine the status. It returns undefined.

**To Reproduce**
```
import vueFilePond from "vue-filepond";
import FilePondPluginFileValidateType from "filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.esm.js";
import FilePondPluginImagePreview from "filepond-plugin-image-preview/dist/filepond-plugin-image-preview.esm.js";

import "filepond/dist/filepond.min.css";
import "filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css";

const FilePond = vueFilePond(
  FilePondPluginFileValidateType,
  FilePondPluginImagePreview
);

console.log(FilePond.Status, FilePond.FileStatus);
```

**Logs**
Both return undefined.

**Expected behavior**
To return an object with status names and codes.

**Information about your project:**
- Your browser and the version: Latest Chrome

- Your operating system: W10

- FilePond version: 4.28.2 and vue-filepond 6.0.3

**Comment by rikschennink** [comment]
You've created your own `FilePond` variable here:

```js
const FilePond = vueFilePond(
  FilePondPluginFileValidateType,
  FilePondPluginImagePreview
);
```

Use this instead to access the enum object.

```js
import { Status, FileStatus } from 'filepond';
```
