### ISSUE TITLE
Get fieldName on remove

### ISSUE THREAD

**Issue by AO-IO** [pqina/vue-filepond#210]
How to get a field name when remove is called?

  ```JAVASCRIPT
remove: (src, load) => {
          // console.log("revert", src);
          load();
        },
```
this only gives the URL of the image.

I have multiple fields and I need the name of each field and send it in the request body of remove.
is it possible?

**Comment by rikschennink** [comment]
I don't know how you'd do it in Vue but for JS it's something like:

```js
const createServer = (fieldName) => {
  remove: (src, load) => {
    // can now use fieldName here
  }
}

FilePond.create({
  server: createServer('my-field')
})
```

**Comment by AO-IO** [comment]
> I don't know how you'd do it in Vue but for JS it's something like:
> 
> ```js
> const createServer = (fieldName) => {
>   remove: (src, load) => {
>     // can now use fieldName here
>   }
> }
> 
> FilePond.create({
>   server: createServer('my-field')
> })
> ```

 If I set custom metadata for the file field and pass the `item` object to the `remove` function in `filepond.js` and then use the metadata that I set in the function .. will that affect the `filepond.js`  (performance, etc..)?

**Comment by AO-IO** [comment]
> I don't know how you'd do it in Vue but for JS it's something like:
> 
> ```js
> const createServer = (fieldName) => {
>   remove: (src, load) => {
>     // can now use fieldName here
>   }
> }
> 
> FilePond.create({
>   server: createServer('my-field')
> })
> ```

im thinking of passing the item to the remove function in filepond.js and get the metadata from there .. is it a good idea?

**Comment by AO-IO** [comment]
> I don't know how you'd do it in Vue but for JS it's something like:
> 
> ```js
> const createServer = (fieldName) => {
>   remove: (src, load) => {
>     // can now use fieldName here
>   }
> }
> 
> FilePond.create({
>   server: createServer('my-field')
> })
> ```

im thinking of passing the item to the remove function in filepond.js and get the metadata from there .. is it a bad idea?

**Comment by rikschennink** [comment]
@AO-IO I'm not sure what you mean, please elaborate
