### ISSUE TITLE
Can't set filepond options when creating component

### ISSUE THREAD

**Issue by GhostNr1** [pqina/vue-filepond#22]
In the vue-fileponds we can only create the component. There would be good to export var _filepond = require('filepond'); so we can set values globaly on filepond as the documentation say https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-options but what I can see we can't do that now. We can only add in plugins but can't set any values when we create this in our main vue file.

**Comment by rikschennink** [comment]
Just published version `2.1.0` you can now import the `setOptions` method. Best to set these before doing anything else.

```js
import vueFilePond, { setOptions } from 'vue-filepond';

setOptions({
    // global options here
});
```

**Comment by GhostNr1** [comment]
Thanks for the fast work on our issue. I have tried to do it like this
`// Create FilePond component
const FilePond = vueFilePond(FilepondPluginFileValidateType, FilepondPluginFileValidateSize, FilepondPluginFileEncode)
setOptions({
  server: {
    url: 'http://localhost:3000'
  }
})`
I have also tried to set the setOptions before const FilePond but it dosn't set the server location when I do the upload. It still try to upload to my webserver (port 8081) instead of our API server

`<file-pond allow-multiple="true" max-files="3" server="api/files/upload"/>`

**Comment by rikschennink** [comment]
Try it like this:

```js
// First set options ( just pass URL directly )
setOptions({
  server: 'http://localhost:3000'
});

// Then create component
const FilePond = vueFilePond(FilepondPluginFileValidateType, FilepondPluginFileValidateSize, FilepondPluginFileEncode)
```

Now you don't have to set the server here.

```html
<file-pond allow-multiple="true" max-files="3"/>
```

**Comment by Konafets** [comment]
@rikschennink This does not seems to work. 

I need to inject the CSRF Token to the request and have tried this first with plain FilePond 

```
const inputElement = document.querySelector('input[type="file"]');
const pond = FilePond.create( inputElement );

FilePond.setOptions({
    server: {
        url: route('account.avatar.upload'),
        process: {
            headers: {
                "X-CSRF-Token": $('input[name="_token"]').val(),
            }
        }
    },
});
```
which worked. Then I switched to the vue component but the csrf token is not included in the request.

Here is my code:

``` 
import vueFilePond, { setOptions } from 'vue-filepond';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.esm.js';

setOptions({
    server: {
        process: {
            headers: {
                "X-CSRF-Token": $('input[name="_token"]').val(),
            }
        }
    }
});

const FilePond = vueFilePond(FilePondPluginImagePreview);
```

Do you have any idea?

**Comment by rikschennink** [comment]
@Konafets If you put a `console.log($('input[name="_token"]').val())` before the `setOptions` statement, does it log the token?

**Comment by Konafets** [comment]
@rikschennink Yes, it does. The `X-CSRF-Token` is not present in the request.

**Comment by rikschennink** [comment]
Okay, I notice the url property is missing, does adding it make any difference or is it just the example snippet. (So I know what to test on Monday morning :-))

**Comment by rikschennink** [comment]
Alright great! 

It does merge options but not only at the top level (so no deep merge). In your situation `"/files/upload"` would then overwrite the earlier server config with the default options.

**Comment by Konafets** [comment]
I managed to do it like this now 

```js
:server="{
    url: route('account.avatar.upload'),
}"
```

Is it somehow possible to wrap the `<file-pond>` component in an custom component?

**Comment by rikschennink** [comment]
Yes, you can always create a custom wrapper.

You could also create a utility function that returns a server config and use that as the value for the server attribute.

**Comment by Konafets** [comment]
Can you point me to an example for a custom wrapper? My main question is, where do I create the component? (calling `const FilePond = vueFilePond( FilePondPluginFileValidateType, FilePondPluginImagePreview );`)

**Comment by rikschennink** [comment]
I think it would basically be a component? And  then in that component you'd call the above method and implement FilePond as usual. Then in your templates you use your custom component.

In it's most basic form that would be this I think:

```vue
const FilePond = vueFilePond( FilePondPluginFileValidateType, FilePondPluginImagePreview );

Vue.component('my-file-pond', {
  template: '<file-pond></file-pond>'
})
```

**Comment by Konafets** [comment]
Ah, thanks again.

**Comment by annymosse** [comment]
the `v-filePond` component isn't reactive ,i have the same troubles :
- `x-xsrf-token` isn't static change each ajax request,whenever it's not geting the new `xsrf-token` value (i solved this point by changing the `filepond.js` core and inject the request by it.
- my server reciving the files at dynamic url (ex:'/uploads/:user_email') and i can't selve this point until now.

**suggestion** : add `axios` lib integration .

**Comment by rikschennink** [comment]
@annymosse You can set a custom processing method and use Axios there to upload the file. That should also supply plenty of flexibility to have a new token each request, also this should make it possible to update the URL as well.

```js
setOptions({
  server: {
    // Called for each file upload
    process: (fieldName, file, metadata, load, error, progress, abort) => {
        // Your custom processing method here
    }
  }
});
```

**Comment by annymosse** [comment]
i didn't try it yet ,can i ask you to post a small example to post a file to the server using idea ?,coz i think there is no params to post the bin file else using so plugin or convert the file into Base64

**Comment by rikschennink** [comment]
You can find an example custom `process` method here:
https://pqina.nl/filepond/docs/patterns/api/server/#advanced

**Comment by annymosse** [comment]
thank you @rikschennink  this advanced example help me

**Comment by annymosse** [comment]
sorry @rikschennink but i coudn't use your solution ,it's still spining without any error report at both sides (server&client),whenerver im still using the browser version not vue-CLI,can you use some real example at codepen or jsFiddle?

**Comment by rikschennink** [comment]
If you can supply a demo on codepen / fiddle / or codesandbox I'm happy to take a look

**Comment by annymosse** [comment]
hi @rikschennink sorry i didn't answer your request coz i switched to `dropzone` ,now im trying again ;
i had unknown problem if i try with axios its work well
```js
new Vue({
   ...,
  data(){
     return {
       ....,
       server:{
          process: (fieldName, file, metadata, load, error, progress, abort) => {
            const formData = new FormData()
            formData.append('papers', file, file.name)
            const CancelToken = axios.CancelToken
            const source = CancelToken.source()

            axios({
              method: 'POST',
              url: '/uploads/temp/'+__UNIQ_ID__,
              data: formData,
              cancelToken: source.token,
              onUploadProgress: (e) => {
                progress(e.lengthComputable, e.loaded, e.total)
              }
            }).then(response => {
              // passing the file id to FilePond
              load(response.file)
            }).catch((thrown) => {
              if (axios.isCancel(thrown)) {
                console.log('Request canceled', thrown.message)
              } else {
                // handle error
              }
            })
            // Setup abort interface
            // return {
            //   abort: () => {
            //     source.cancel('Operation canceled by the user.')
            //     abort()
            //   }
            // }
          },
          revert:(uniqueFileId, load, error)=>{
            axios({method: 'DELETE',url: '/uploads/temp/'+__UNIQ_ID__}).then(res => {
              load()
            })
          }
        }
     }
  }
})
```
whenever i tried lots to post same files the server still rejecting them with 403 status
```js
new Vue({
   ...,
  data(){
     return {
       ....,
       server: {
          url:"/uploads/temp/"+__UNIQ_ID__,
          process: {
            headers: {
              "X-XSRF-TOKEN": ((name)=>{var value = "; " + document.cookie;var parts = value.split("; " + name + "=");if (parts.length == 2)return parts.pop().split(";").shift()})("XSRF-TOKEN")
            },
            withCredentials:true
          }
        }
     }
  },
  mounted(){
     /**
        * with or without interval:
        * ================
        * im using interval only to make sure the header is updated with any new xsrf token
        */
     setInterval(()=>{
        this.server.process.headers["X-XSRF-TOKEN"]=((name)=>{var value = "; " + document.cookie;var parts = value.split("; " + name + "=");if (parts.length == 2)return parts.pop().split(";").shift()})("XSRF-TOKEN")
      },1000)
  }
})
```

**Comment by rikschennink** [comment]
Why are you not setting the headers inside the axios processing call?

**Comment by annymosse** [comment]
> Why are you not setting the headers inside the axios processing call?

coz `axios` set the headers automatically

**Comment by rikschennink** [comment]
then I don't know what's going on, the 403 suggests your server is not allowing the post, wether that is because of too much requests or the requests having incorrect headers I don't know.

**Comment by annymosse** [comment]
@rikschennink there's a single request coz im using devtools with break point to the route bellow `/uploads/temp/` and i had confirmed if does it sending the `xsrfToken` or not , you can try it via `expressJs` or as am i using `AdonisJS` (not sure :100:  ,but any server using `xsrfToken` protection)

**Comment by rikschennink** [comment]
If the tokens are in the request than I don't think this has to do with FilePond, FilePond is simply firing the request nothing more.

**Comment by annymosse** [comment]
@rikschennink  thanks after all ,but until now I don't know why i can post the file(s) via `axios` whenever i can do the same via `Filepond` only if i turn the `xsrfToken` protection, i think we must know the reason behind this ponit.

**Comment by juno0424** [comment]
The easiest way to include CSRF token in headers is apply it on server binding.

```
<file-pond
        name="upload"
        ref="pond"
        label-idle="Drop files or clicks here..."
        v-bind:allow-multiple="true"
        accepted-file-types="image/jpeg, image/png, image/gif"
        :server="{
          url: currentUrl + '/uploads',
          process: {
            headers: {
              'X-CSRF-TOKEN': csrfToken
            }
          }
        }"
        v-bind:files="myFiles"
        v-on:init="handleFilePondInit"
        class="mt-1"
      />
```

at the data() set `csrfToken: document.querySelector('meta[name="csrf-token"]').content`

**Comment by dyerrington** [comment]
@juno-w does this only work for single requests / uploads?  Doesn't the csfr token need to be unique per request?

**Comment by nokafor2** [comment]
Also, I want to know if it's possible to append a text input to each image uploaded during preview and give it a caption. Thanks
