### ISSUE TITLE
[Bug] __unset__ props Vue Filepond v7

### ISSUE THREAD

**Issue by Tofandel** [pqina/vue-filepond#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated Vue FilePond, FilePond, and all plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

`__unset__` default prop value is being displayed in HTML attributes, which wasn't the case in v6 (vue 2)

![image](https://user-images.githubusercontent.com/6115458/157048946-46d9f901-b9c4-4e16-82e9-8f0eaaf40871.png)

This is also a big problem if using the validate-file-type plugin and not declaring an accepted type, all files will be rejected instead of all accepted
![image](https://user-images.githubusercontent.com/6115458/157067024-b282bd9a-2559-4ec9-a6bc-edf688dc06a8.png)

### Reproduction

https://codesandbox.io/s/vue-filepond-live-demo-forked-7fpymj?file=/src/main.js

### Environment

```markdown
- Vue version: 3
```

**Comment by Tofandel** [comment]
As I'm not exactly sure why `__unset__` has been added as default value instead of just leaving it `undefined`, I made a PR keeping it, but removing it entirely would be the way to go there, as I don't think it serves a good purpose

**Comment by rikschennink** [comment]
It's been a while but if I remember correctly it's set to `__unset__` because `undefined` is also a value that can be passed to props and I needed a way to know if a prop was passed.

**Comment by Tofandel** [comment]
Do you have an example or use case of when would `undefined` be passed to a prop?

Because with a quick test, a prop without a type passed like a boolean prop (eg: `<Filepond allow-multiple>`) will be an empty string and not undefined so that seems like something that's just not needed and instead causes problems

**Comment by sammyaxe** [comment]
having capture="__unset__" prevents safari from prompting image gallery, files or camera select and defaults it to capture, there should be no capture tag by default.

**Comment by rikschennink** [comment]
Pushed release `7.0.3` which should fix the issue.
