### ISSUE TITLE
Removefile is async?

### ISSUE THREAD

**Issue by skayablars** [pqina/vue-filepond#25]
**Problem:** I have a wrapper with the filepond component after somebody removes an image I want to update a data property.  So I have a listener on removefile and call a function that check the dom for any input element but after I remove the image the element stays there, my solution is to wait some seconds and then read the document but I think that this function should be emitted when the input are removed from the dom or return a promise.

**Comment by rikschennink** [comment]
Can you try with version `1.8.0` of FilePond? It contains some changes that make the events async.

**Comment by Hellek** [comment]
@rikschennink can you update vue-filepond package.json? For
```
"dependencies": {
    "filepond": "^1.8.0"
}
```
For now it 1.7.* and old problems fixing can be solved just manually

**Comment by rikschennink** [comment]
@Hellek done!

**Comment by skayablars** [comment]
Hi, I updated all filepond and vuefilepond dependencies. However when the removedfiles event has emitted the fieldset with the image still exists.

**Comment by Hellek** [comment]
@skayablars Can you show an example of your component code?

@rikschennink rick, I observe that you include "filepond-master" to vue-filepond by including node_modules subfolder, is it temporary solution?
I asking cause there was some hardcode changes for styles
from `import 'filepond/dist/filepond.min.css';`
to `import 'vue-filepond/node_modules/filepond/dist/filepond.min.css';`

**Comment by rikschennink** [comment]
@skayablars it’s possible that the elements are still there for a short moment as they animate out of view. What are you doing with them?

@Hellek I’m not sure what you mean? I’ve only upped the version number in the package.json file :-)

**Comment by Hellek** [comment]
@rikschennink problem is solved my manual deleting of vue-filepond package + "npm update". The issue was that filepond was located at node_modules -> which was inside vue-filepond folder like this `vue-filepond/node_modules/filepond`
After deletion and update structure of packages as must be)
