### ISSUE TITLE
remove all files in vue3 script environment

### ISSUE THREAD

**Issue by chance-up** [pqina/vue-filepond#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated Vue FilePond, FilePond, and all plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

to remove all files, 
want access the Filepond object and use 'removeFiles' method.

but i cant access filepond object
(using ref)

Other examples say to use this.$ref.pond.removeFiles() , but cannot use this.$ref in the vue3 script method.
How should I acess it?

`
<temlplate>
    <FilePond
      ref="pond"
      instant-upload="false"
      label-idle="Drop files here..."
      :allow-multiple="false"
      :credits="'false'"
      allow-revert="false"
      accepted-file-types=".java"
      @addfile="addFile"
      @error="onFilesError"
    />
</temlplate>

<script setup lang="ts">
...

const FilePond = vueFilePond(FilePondPluginFileValidateType);

const pond = ref<HTMLDivElement | null>(null);

const remove = () => {

**pond.value.pond.removeFiles()**

}

</script>`

### Reproduction

always

### Environment

```markdown
- Device: Mac 
- OS: 12.4
- Broser: Chrome 102.
- Vue version: vue 3.2.36 + vite 2.9.9
- VueFilepond version : 7.0.3
```

**Comment by rikschennink** [comment]
Hm that should work.

The FilePond instance is stored in `this._pond`, I don't have a workstation at hand but I'd try `console.log(this.$refs.pond)` and see what's in there. I suspect you can also call it like this `this.$refs.pond._pond.removeFiles()`

**Comment by chance-up** [comment]
When I access it with 'pond.value._pond.removeFiles()', it works normally.
I'm sorry I didn't understand deeply and asked a question.

Thanks..
