### ISSUE TITLE
[Bug] Custom load function isn't triggering

### ISSUE THREAD

**Issue by Tauromachian** [pqina/vue-filepond#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated Vue FilePond, FilePond, and all plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Custom load function is not triggering. Notice that I also used the process function which is working.

### Reproduction

I tried the most basic configuration I could find.
```js
<template>
  <div id="app">
    <file-pond
      name="test"
      :allow-multiple="true"
      :server="myServer"
    ></file-pond>
  </div>   
</template>

<script>
// Import filepond styles
import "filepond/dist/filepond.min.css";

// import vue filepond from vue-filepond
import VueFilepond from "vue-filepond";

const FilePond = VueFilepond();

export default {
  name: "App",
  components: {
    FilePond,
  },
  data() {
    return {
      myServer: {
        process: (asdf, asd, as, load) => {
          console.log("zxvcxcx");
          // simulates uploading a file
          setTimeout(() => {
            load(Date.now());
          }, 1500);
        },
        load: (source, load) => {
          console.log("asdf");

          // simulates loading a file from the server
          fetch(source)
            .then((res) => res.blob())
            .then(load);
        },
      },
    };
  },
};
</script>
```

### Environment

```markdown
- Device: Computer
- OS: Linux
- Browser: Brave, Polypane, Mozilla Firefox
- Vue version: 2.6.14
```

**Comment by rikschennink** [comment]
It will only trigger for local files.
https://pqina.nl/filepond/docs/api/instance/properties/#files

**Comment by Tauromachian** [comment]
That's confusing. In the docs it states:

>  the load end point is used to restore already uploaded server files

Also it may be worthy to mention that adding a new file to the files array triggers the process function. When I load an already upload file into filepond(as a visual aid to my users) it triggers the process function. That results on files being repeated over and over on the server
