### ISSUE TITLE
What is the name of the event after successful upload? How do I get the file returned after upload？

### ISSUE THREAD

**Issue by BiYuqi** [pqina/vue-filepond#27]

**Comment by rikschennink** [comment]
https://pqina.nl/filepond/docs/

**Comment by xgenvn** [comment]
I myself found it a bit confusing while reading the doc (due to naming issue).
The event we can used are:
- `onprogressfile` -> `@progressfile` (a file finished uploaded without error)
- `onprogressfiles` -> `@progressfiles` (all files finished without error)

Hope this help others if it's not obvious explaining by the docs.

**Comment by svennerberg** [comment]
Actually I think it's:

```
* onprocessfile -> @processfile
* onprocessfiles -> @processfiles
```
This tripped me up too, but @xgenvn pointed me in the right direction

Another thing that tripped me up at first was that the first argument it returns is an error object (which is null if everything went well) and the uploaded file as the second argument. A bit unconventional I think.

**Comment by rikschennink** [comment]
@svennerberg It's based on node.js readFile

```js
fs.readFile('/etc/passwd', (err, data) => {
  if (err) throw err;
  console.log(data);
});
```

https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback

**Comment by svennerberg** [comment]
@rikschennink Ah, that explains it! Thanks!

**Comment by owalid** [comment]
Hello !
Neither `@progressfiles` nor `@processfiles` works for me, how do you use it on a filepond view instance ?
Thanks !

**Comment by jimmiejackson414** [comment]
Any update on this? I've tried variations of `@processfile`, `@progressfile`, `@onprocessfile`, and `@onprogressfile`, and none seem to be working.

**Comment by rikschennink** [comment]
@jimmiejackson414 See this codesandbox, `processfile` is called.
https://codesandbox.io/s/vue-filepond-v9ijm?file=/src/components/FilePond.vue

**Comment by vesper8** [comment]
@rikschennink processfile is called after each file is done uploading. But I want to call a function after ALL files are done uploading. Could you please clarify, if the user picks 4 files to upload at once.. how can I know when all 4 files are completely done uploading? Many thanks

**Comment by rikschennink** [comment]
@vesper8 I've updated the sandbox, it clearly fires both events.
https://codesandbox.io/s/vue-filepond-v9ijm?file=/src/components/FilePond.vue

**Comment by vesper8** [comment]
Hi @rikschennink,

Thank you for your reply.

It does work if I replace my whole server configuration with the one in your demo:

```
        process: (name, file, meta, load) => {
          load(Date.now());
        },
```

But with my configuration then `processfile` is triggered, and the files do upload correctly, but `processfiles` however is never triggered.

This is what my process command looks like in my server config:

```
        process: {
          headers: {
            Authorization: `Bearer ${this.$auth.token()}`,
          },
        },
```

I guess the problem is that I am not calling `load` ? But I don't know how to set the headers and call `load`.. I guess I don't know the correct syntax to do both

This is my whole server config:

```
      serverOptions: {
        url: `${this.$api}/api/v1/profile/images`,
        process: {
          headers: {
            Authorization: `Bearer ${this.$auth.token()}`,
          },
        },
        revert: {
          headers: {
            Authorization: `Bearer ${this.$auth.token()}`,
          },
        },
        load: (source, load, error, progress, abort, headers) => {
          const url = source;
          const myRequest = new Request(url);
          fetch(myRequest).then((response) => {
            response.blob().then((myBlob) => {
              load(myBlob);
            });
          });
        },
        remove: (source, load, error, progress, abort, headers) => {
          this.$http
            .delete(`${this.$api}/api/v1/profile/images`, {
              params: { source },
            })
            .then((response) => {
              console.log(response.data);
              if (response.data === 'deleted') {
                load();
              } else {
                Bus.$emit('ok-box:show', {
                  title: 'Error',
                  // body: err.response.data.errors[0],
                  body: response.data,
                  okVariant: 'danger',
                });
                error();
              }
            });

          return true;
        },
      },
```

Could you please tell me how I can set the headers and call `load` inside the `process` so that my `processfiles` will be triggered too?

Many thanks!

**Comment by vesper8** [comment]
So I found from another issue that you can set the headers globally by adding 

```
          headers: {
            Authorization: `Bearer ${this.$auth.token()}`,
          },
```

Directly under the server options. I thought this would solve my problem now

So I tried commenting out my process block completely. If I do that.. then my file gets uploaded as it did before.. but `processfiles` is never called

If I add a process block, such as adding the demo one in your sandbox, then my file is no longer getting uploaded, and still `processfiles` is also not called

I just want to know when all files are done uploading... it was almost fully working already.. I shouldn't have to write my own custom process block to upload to my server.. the default is working fine.. but it's like the default doesn't call `processfiles` when it's all done when uploading to a server =/

**Comment by rikschennink** [comment]
Just tested to be sure, but this works fine here. Make sure your servers return a unique id for each file and return correct http status code.
<img width="476" alt="Screenshot 2021-05-28 at 12 15 32" src="https://user-images.githubusercontent.com/1132575/119969100-6da9ee80-bfae-11eb-9a33-ec0ec3a9e807.png">
