### ISSUE TITLE
__vite_ssr_import_1__.default is not a function

### ISSUE THREAD

**Issue by okoliken** [pqina/vue-filepond#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated Vue FilePond, FilePond, and all plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I am using vueFilePond in nuxt 3, it works initially, but when I reload the page it throws this error '500
__vite_ssr_import_1__.default is not a function'. I have installed the necessary packages.

### Reproduction

`<script>
import vueFilePond from "vue-filepond";

import "filepond/dist/filepond.min.css";
 import "filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css";

  // Import image preview and file type validation plugins
  import FilePondPluginFileValidateType from "filepond-plugin-file-validate-type";
  import FilePondPluginImagePreview from "filepond-plugin-image-preview";

  const FilePond = vueFilePond(
    FilePondPluginFileValidateType,
    FilePondPluginImagePreview
  );
export default {
  components: {
    FilePond,
  },
};
</script>`

### Environment

```markdown
- Device: Macbook Pro (2015)
- OS: IOS
- Broser: Chrome
- Vue version: vue3, nuxt 3
```

**Comment by lin69x** [comment]
Helloy! Please share how the problem was solved
