### ISSUE TITLE
old index.d.ts in npm release [Feature] 

### ISSUE THREAD

**Issue by MangeS** [pqina/vue-filepond#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

setOptions  interface is not present in ts types when installing current version(7.0.3) from npm

### Describe the solution you'd like

generate a npm release that includes newest version of index.d.ts

### Describe alternatives you've considered

defining the interface ourselves

**Comment by simonmaass** [comment]
+1

**Comment by rikschennink** [comment]
Seems to be the same `index.d.ts` as the gh repository? I'd need more information to pick this up.
