### ISSUE TITLE
Working with server for filename

### ISSUE THREAD

**Issue by davutkara** [pqina/vue-filepond#28]
Hi, I want to control the name of file, first when file added I asked server for appropriate name then I use rename plugin, but plugin callback function can't get the value from promise. 

```js
  fileNameRequest: async function (file) {
      let filename = file.basename
      try {
        return await this.$fetch.post(process.env.UPLOAD_URI + '/uploadName', {
          filename: file.basename
        }).then(async (data, err) => {
          if (data.status === 200) {
            let result2 = await data.json().then((data) => {
              filename = data.name
              return filename + file.extension
            }).catch(() => {
              this.$root.$children[0].showErrorMsg()
            })
            return result2
          } else {
            this.$root.$children[0].showErrorMsg()
          }
        })
      } catch (err) {
        this.$root.$children[0].showErrorMsg()
      }
    }
```
When I use this funciton file name is like Object Promise

I tried a lot of different way.

![image](https://user-images.githubusercontent.com/10008440/41820269-c4771782-77d7-11e8-9a39-1d45bd7eade1.png)

**Comment by davutkara** [comment]
Function directly cast the return value to string. I am really confused :)

**Comment by rikschennink** [comment]
@davutkara It expects a synchronous function, you'll have to return a string ( you're returning a Promise and it'll just turn that into a string instead ).

**Comment by rikschennink** [comment]
@davutkara You could use a custom process method instead?
