### ISSUE TITLE
[Bug] Infinite height growth using multiple option.

### ISSUE THREAD

**Issue by jason-beach** [pqina/vue-filepond#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated Vue FilePond, FilePond, and all plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I have encountered an issue related to the layout management, specifically concerning infinite height growth of the `.filepond--root` element.

When using the FilePond component (Vue) with the allowMultiple option enabled, the height of the `.filepond--root` element grows indefinitely when I only add 1 file. This behavior leads to an infinite scroll situation, where the container's height continues to increase without any apparent constraints.

### Reproduction

1. Initialize FilePond with `allowMultiple` set to `true`.
2. Add a file to the component.
3. Observe that the height of the `.filepond--root` element grows continuously, without stopping.

Here's a video: https://app.screencast.com/v4qSjtpXHRaJs

Here's my implementation:
```
<file-pond
  ref="pond"
  accepted-file-types="image/*"
  allow-multiple="true"
  class-name="my-pond"
  credits="false"
  label-idle="<span class='filepond--label-action'>Click to upload</span> or drag and drop files."
  max-files="3"
  v-on:addfile="handleFilesAdded"
  v-on:removefile="handleFilesRemoved"
/>
```

### Environment

```markdown
- Device: Desktop iMac
- OS: Sonoma 14.5
- Browser: Chrome Version 127.0.6533.73 (Official Build) (x86_64)
- Vue version:  "vue": "^3.4.35"
```

**Comment by rikschennink** [comment]
I wonder if it still  happens if you disable any custom styles assigned to filepond.

If that makes no difference, what happens if you remove other style sheets.

I suspect there is some style problem causing the height calculations to go wrong.

Kind regards,

Rik | PQINA

PQINA BV
Sint Willibrordusstraat 16
5502 BH Veldhoven
The Netherlands

**Comment by jason-beach** [comment]
@rikschennink , thanks for the thoughts. When I reviewed the custom styles I applied for the filepond area there was an `h-full` tailwindcss class applied in order to center the `filepond--drop-label` b/c in some places I've created a custom height and wanted the label to be in the center. I've removed that for now which fixes the issue.

Appreciate the quick reply!

**Comment by rikschennink** [comment]
@jason-beach glad to hear that fixed it 👍
