### ISSUE TITLE
Acces FilePond instance

### ISSUE THREAD

**Issue by weislanes** [pqina/vue-filepond#3]
Hey,

Is there any way to access the Filepond instance in Vue? This would be useful in general, but also specifically I need to clear the thumbnail preview after an image is uploaded and from the docs it looks like 'removeFile' might do the trick. (Unless there's a better way?).

**Comment by rikschennink** [comment]
Hi!

The FilePond instance methods are automatically added to the Vue component when it's created. If you set a `ref` you can access them directly on the property. In the example below `this.$refs.pond.removeFile()` is available.

```HTML
<template>
  <div id="app">

    <FilePond ref="pond" @init="handleFilePondInit"/>

  </div>
</template>

<script>
// Import FilePond
import FilePond from 'vue-filepond';

export default {
    name: 'app',
    methods: {
        handleFilePondInit: function() {
            console.log('FilePond has initialized');
            
            // FilePond instance methods are available on `this.$refs.pond`
        }
    },
    components: {
        FilePond
    }
};
</script>
```

**Comment by weislanes** [comment]
Awesome, thank you. Just switched out dropzone for Filepond. Really nice work!

**Comment by rikschennink** [comment]
Waw nice! Thanks @weislanes!
