### ISSUE TITLE
Server and server url prop do not respond to changes

### ISSUE THREAD

**Issue by jaydenrsoni** [pqina/vue-filepond#31]
### Summary
Thanks for a great component!

I am trying to restrict the ability to upload until a certain state is reached by initializing the server url prop to '', and later setting it to the actual server url. However, the FilePond instance still uses the blank url when processFile() is called. 

Alternatively, is there a better way to restrict the ability to upload based on state? (preferably without having to use custom server methods--the rest of the functionality is perfect for my needs!!)

### How to reproduce
Final State:
![image](https://user-images.githubusercontent.com/36484717/42598475-2dda10c6-8511-11e8-82f1-625cdacd5554.png)

Initial State:
```html
<file-pond
            ref="pond"
            max-files=1
            accepted-file-types="text/plain"
            fileValidateTypeLabelExpectedTypes="Must be a plain text file"
            instant-upload="false"
            allow-replace="false"
            :server="server"
            @addfile="handleAddFile"
            @removefile="handleRemoveFile"
            @processfilestart="handleProcessFileStart"
            @processfileabort="handleProcessFileAbort"
            @processfile="handleProcessFile"
          ></file-pond>
```
```javascript
data: () => ({
    dialog: false,
    loading: false,
    pagination: { sortBy: 'scanStatus', descending: true },
    headers: [
      { text: 'Serial Number', value: 'num' },
      { text: 'Latitude', value: 'latitude' },
      { text: 'Longitude', value: 'longitude' },
      { text: 'Elevation', value: 'elevation' },
      { text: 'Site Name', value: 'site' },
      { text: 'Scan Time', value: 'date' },
      { text: 'Edit/Delete', value: 'edit', sortable: false, align: 'center' },
      { text: 'Status', value: 'scanStatus' },
    ],
    server: {
      url: '',
      process: '/',
      revert: '/',
      restore: null,
      load: null,
      fetch: null,
    },
    firstLine: '',
    scans: [],
    statusString: 'start',
    tmpStatusString: '',
    editedIndex: -1,
    editedItem: {
      site: '',
      date: '',
    },
  }),
```

### Expected behaviour

I would expect to receive the above error only before server url is set (afterwards it should be fully functional, as it is when I initialize the server prop to the correct url to begin with). Thanks for any help or insight you can provide!

**Comment by rikschennink** [comment]
I'm not sure how you're setting the server object, and maybe you're already doing this, but can you try overwriting the entire server property instead of only the url?

`server = { url:'new-url' }` instead of `server.url = 'new-url'`

**Comment by rikschennink** [comment]
Reading the issue again I think it would be better if I add something like a `allowProcess` property that toggles the upload button. That way you could enable it when you're ready. Would still require the above server update suggestion to work though.

**Comment by jaydenrsoni** [comment]
Setting the whole server property instead of just the url works! Thanks for the tip!

**Comment by jaydenrsoni** [comment]
An allowProcess property would also be helpful. From my understanding, that functionality can currently be achieved through setting the server "process" property to null, but an explicit property similar to "allowRevert" to control the UI display separately from the functionality may be helpful for some users. For me, the current setup will work just fine! Thanks again for your notes!

**Comment by jaydenrsoni** [comment]
Actually, upon looking at things again, setting the "process" property to null doesn't quite do what I'm looking for. Seeing as my initial issue has been solved though, I'll open a new request.

**Comment by rikschennink** [comment]
Will close this one and add `allowProcess` to the roadmap.

**Comment by creazy231** [comment]
@rikschennink Hey man, I have the same problem but cant figure out how you fixed it. Could you provide me any information?

**Comment by rikschennink** [comment]
Accidentally opened the issue. :)

**Comment by rikschennink** [comment]
@creazy231 I've lost track of this.

**Comment by lpeliberty** [comment]
hello guys, just hide the button is a really bad practice...
A simple trick to disable upload button and other features around the upload is to set `process` property to `null` in server config : 
```js
<FilePond
    server={{
      // Disable possibility to upload file
      process: null,
    }}
/>
```
This is my React solution , just adapt it :wink:

**Comment by hanzlahabib** [comment]
@lpeliberty  how do you retrieve file once its set to state?
i tried to follow the official documentation examlple but at time of assigning file in data object it gives 
```
File: [{_relativePath: ""}]

```
