### ISSUE TITLE
Minor documentation error?

### ISSUE THREAD

**Issue by jaydenrsoni** [pqina/vue-filepond#32]
Not sure if this is the best place to note this, but I think the "processfileundo" is actually referenced by "processfilerevert" at least from a Vue context. That, or I'm misunderstanding the description--but "processfilerevert" is a working event that is not noted!

![image](https://user-images.githubusercontent.com/36484717/42600238-793107d2-8516-11e8-9dde-0e7f763ed046.png)

![image](https://user-images.githubusercontent.com/36484717/42600261-8c321b6e-8516-11e8-9589-c25c2c2467d0.png)

**Comment by rikschennink** [comment]
Yea it should be `"processfilerevert"`, please feel free to submit a PR here:
https://github.com/pqina/filepond-docs
