### ISSUE TITLE
Feature Request: allowProcess property

### ISSUE THREAD

**Issue by jaydenrsoni** [pqina/vue-filepond#34]
### Summary
I would like the ability to toggle the presence of an upload button, similar to the allowRevert property.

![image](https://user-images.githubusercontent.com/36484717/42657439-0349e0ae-85d7-11e8-8f39-205ffcd55a89.png)

Currently the above display can be achieved by setting the "server.process" property to null, but this also gets rid of the ability to remove files. If possible, I would still like to be able to use the "x" icon on the left of the component:

![image](https://user-images.githubusercontent.com/36484717/42657555-654edc0a-85d7-11e8-8b56-3fca4f7589ac.png)

### How to reproduce

```html
<file-pond
            ref="pond"
            max-files=1
            accepted-file-types="text/plain"
            fileValidateTypeLabelExpectedTypes="Must be a plain text file"
            instant-upload="false"
            allow-replace="false"
            allow-revert="false"
            :server="server"
            @addfile="handleAddFile"
            @removefile="handleRemoveFile"
            @processfilestart="handleProcessFileStart"
            @processfileabort="handleProcessFileAbort"
            @processfilerevert="handleProcessFileUndo"
            @processfile="handleProcessFile"
          >
          </file-pond>
```
```javascript
data: () => ({
    server: {
      url: '',
      process: null,
      revert: null,
      restore: null,
      load: null,
      fetch: null,
    },
}
```

### Additional information

It would be extremely helpful to separate the adding/removing of files functionality from the processing/reverting functionality. Personally, I'm using this component to fetch data from a file directly for use on the webpage, so features like the ability to remove an incorrectly selected file and the filetype verification plugin are very helpful, whereas the ability to upload the file to a server is actually less necessary, and something I might handle outside of the component. This may be a niche use case, but I think it may apply to others too! Thanks so much for any additional functionality you can provide.

**Comment by rikschennink** [comment]
Will look into this, it shouldn't hide the remove button, so seems to be a bug.

**Comment by jaydenrsoni** [comment]
In the new version, when I set "server.process" to null and "server.url" to the url of my external api, the upload button is now still visible, and when I click on it I get the following behavior:

![image](https://user-images.githubusercontent.com/36484717/42703173-9746f98c-8680-11e8-98eb-48aab0d7fc4d.png)

The undo/cancel operation does not work from this state, and from what I can tell, the component does not seem to be communicating with the server. In my opinion, there are three potential ways to go in terms of expected behavior.

1. (The most involved but ideal option) Clicking the process button with "server.process" set to null simply lends no result, or better yet produces an error label within the component. This would be similar to the current behavior of setting "server.revert" to null with "allowRevert" set to true.

Then, again similar to the revert protocol, one could set an "allowProcess" property to false in order to remove the upload arrow from the UI of the component entirely.

2. Setting "server.process" to null both disallows processing functionally and removes the upload arrow from the UI.

3. Setting "server.process" to null disallows processing functionally. Clicking the arrow in the UI either does nothing or produces an editable error label within the component.

Thank you very much for your quick responses and willingness to make changes! And I'm sorry for any lack of clarity in my requests or comments--I am still in the process of figuring out the best way to use this component for my needs and you have been very helpful throughout.

I'm going to try using the custom configuration of server functions to achieve my desired "process" capability; if that doesn't work out, it would be very nice to have Option 2 above enabled at least so I could continue to use FilePond despite handling the actual processing/uploading of information separately. I definitely understand though if that is too much to ask, or if you want to wait for more information on the success of my custom configuration attempts before proceeding further. 

Thanks again!

**Comment by jaydenrsoni** [comment]
Update: advanced server configuration has done the trick for me. You're (obviously) still welcome to introduce any new functionality you'd like, but my applications working as desired! Feel free to close this issue--sorry for flip-flopping so much. Thanks again for your time and attention, as well as for designing and maintaining such a helpful component!

**Comment by rikschennink** [comment]
Alright, thanks for letting me know, will close this one for now.
