### ISSUE TITLE
Showing Image when component is Loaded

### ISSUE THREAD

**Issue by jdriesen** [pqina/vue-filepond#35]
Hi All,

First of all, congratz to the devs of this component !
It's really GREAT.

I've a small question about "showing an image when component is loaded"

Please take a look at the https://pqina.nl/filepond/#examples page
More in particular...  the "Profile Picture Selection" page.

This assumes there is NO picture selected when the page loads...
But suppose there IS already a picture available (when the component loads" ...) 
How do I show the "already existing image" ?

Or in other words... how can I show a picture on initialization of the component ?

Thanks in advance for your reply,

Johnny Driesen
Belgium
(newbie)

**Comment by rikschennink** [comment]
Hi Johnny! You're most welcome, thanks for using FilePond for one of your projects.

You'll have to add the [FilePond Image Preview plugin](https://github.com/pqina/filepond-plugin-image-preview), then you can use the `files` property to set the initial file. The Image Preview plugin should automatically pick it up and show the image, you will have to set up a `load` end-point in the `server` property which FilePond will use to get the image data from the server. More information can be found in the [Server Configuration](https://pqina.nl/filepond/docs/patterns/api/server/) section of the docs.

**Comment by Doaabawab** [comment]
Hi All,

It is really a very nice component, I like it and use it on my project.
But Unfortunately, I am facing a problem with preview image on load, I have included the FilePond Image Preview plugin, and my backend returns the file URL place, however, the image doesn't show on load. 

Am I forgetting any priority and I have to configure it? or there is a problem with my settings,
Here is my code.

        FilePond.setOptions({
	   server: {
	        url: 'URL',
	       process: 'ADD Method',
	      //   load: 'URL',
	       load: {
	            url: 'URL',
	            method: 'GET',
	            withCredentials: false,
	            headers: {
	            	'Content-Disposition':'inline'
	            },
	           onload: function(response) {
	                return response.key;
	            },
	            onerror: function(response) {
	                return response.data;
	            }
	        }
	    }
	});


         const pond = FilePond.create({
		    files: [
		        {
		            // the server file reference
		            source: 'GETATTACHMENT',
					
		            // set type to limbo to tell FilePond this is a temp file
		            options: {
		                type: 'local'
		            }
		        }
		    ]
		});

Thanks alot for your efforts and for this magical component.
And Thanks for your reply.

Doaa

**Comment by rikschennink** [comment]
Thanks! Glad you like it!

The `load` end point should return the image binary data, it seems to be returning an image key.

**Comment by achyutgauli** [comment]
my preview image working fine when clicking on "Browse input field" but I want to see saved image on storage by default and then later on change image and save it... using filepond..
Here is my code:
![screenshot 58](https://user-images.githubusercontent.com/21071463/48599686-e7e66a80-e990-11e8-9775-33acd9d50531.png)
![screenshot 59](https://user-images.githubusercontent.com/21071463/48599687-e87f0100-e990-11e8-8075-492879b19804.png)
In Index.blade.php
<script>
    FilePond.registerPlugin(
        FilePondPluginFileEncode,
        FilePondPluginFileValidateType,
        FilePondPluginImageExifOrientation,
        FilePondPluginImagePreview,
        FilePondPluginImageCrop,
        FilePondPluginImageResize,
        FilePondPluginImageTransform
    );
    // Select the file input and use
    // create() to turn it into a pond
    FilePond.create(
        document.querySelector('input[type="file"]'),
        {
    labelIdle: `Drag & Drop your picture or <span class="filepond--label-action">Browse</span>`,    
    imagePreviewHeight: 170,
    imageCropAspectRatio: '1:1',
    imageResizeTargetWidth: 200,
    imageResizeTargetHeight: 200,
    stylePanelLayout: 'compact circle',
    styleLoadIndicatorPosition: 'center bottom',
    styleButtonRemoveItemPosition: 'center bottom',

    files: [
        {
            // the server file reference
            source: '12345',

            // set type to local to indicate an already uploaded file
            options: {
                type: 'local',

                // stub file information
                getFile: {
                    name: 'photo',
                    size: 3001025,
                    type: 'image/jpg, image/png, image/jpeg, image/gif'
                },

                // pass poster property
                metadata: {
                    // poster: './images/profiles/1_everest2.jpg'
                    poster: '{{ asset('storage/images/profiles/'.$user->photo) }}'
                }
                
            }
        }
    ]
        }
    );
    
    
</script>

In profile.blade.php
<img src="{{ asset('storage/images/profiles/'.$user->photo) }}"/>
                       <input type="file"
                       class="filepond" 
                       name="photo"                                           
                       accept="image/png, image/jpeg, image/gif"/>


How can I use img src in input field so that storage image shown by default and change later on as user wish and save it.

**Comment by achyutgauli** [comment]
<img src="{{ asset('storage/images/profiles/'.$user->photo) }}"/>
 <input type="file"
                       class="filepond" 
                       name="photo"                                           
                       accept="image/png, image/jpeg, image/gif"/>

**Comment by achyutgauli** [comment]
img src="{{ asset('storage/images/profiles/'.$user->photo) }}"/
<input type="file"
                       class="filepond" 
                       name="photo"                                           
                       accept="image/png, image/jpeg, image/gif"/>

**Comment by rikschennink** [comment]
@achyutgauli I've formatted your code blocks, please do so next time using backticks.

You need to add the FilePoster plugin if you want to use the poster metadata property. Otherwise you have to setup the server.load endpoint, see [server docs](https://pqina.nl/filepond/docs/patterns/api/server/).

**Comment by achyutgauli** [comment]
Thank you so much for your response
*Achyut Gauli*
*Freelancer WordPress Developer| Digital Marketing Experts | SEO Specialist*
*Phone: +977 9843512746*
*Email: achyutgauli@gmail.com <achyutgauli@gmail.com>*
*Website: www.enlightnepal.com <http://www.enlightnepal.com>*

**Comment by achyutgauli** [comment]
Thank you so much for your response. I already used File Poster Plugin along with other CSS and JS
CSS:
<link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-file-poster/dist/filepond-plugin-file-poster.css" rel="stylesheet">
JS:
<script src="https://unpkg.com/filepond/dist/filepond.min.js"></script>
<script src="https://unpkg.com/jquery-filepond/filepond.jquery.js"></script> -->
<script src="https://unpkg.com/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.js"></script>

<script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>

<script src="https://unpkg.com/filepond-plugin-file-metadata/dist/filepond-plugin-file-poster.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-metadata/dist/filepond-plugin-file-metadata.js"></script>
<script src="https://unpkg.com/filepond/dist/filepond.js"></script>)

**Comment by achyutgauli** [comment]
Note: Sorry I was not able to format my script but I would learn for it...
Thank you so much for your response. I already used File Poster Plugin along with other CSS and JS
CSS:
<link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-file-poster/dist/filepond-plugin-file-poster.css" rel="stylesheet">
JS:
<script src="https://unpkg.com/filepond/dist/filepond.min.js"></script>
<script src="https://unpkg.com/jquery-filepond/filepond.jquery.js"></script> -->
<script src="https://unpkg.com/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.js"></script>

<script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>

<script src="https://unpkg.com/filepond-plugin-file-metadata/dist/filepond-plugin-file-poster.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-metadata/dist/filepond-plugin-file-metadata.js"></script>
<script src="https://unpkg.com/filepond/dist/filepond.js"></script>


But Still Got same issue although my preview work fine. I just want to automatically see the previous stored image, I have saved on storage section in Laravel after pressing saved Button that I have. But image not seeing until I click on Drag & Drop your picture or <span class="filepond--label-action">Browse</span> section...and not saving image as well when I pressed saved button through input field using filepond but that work fine through using just input field without using filepond class... What Should I do? to fix these issues.

**Comment by rikschennink** [comment]
I don't see the poster plugin the `registerPlugin` call.

```js
FilePond.registerPlugin(
        FilePondPluginFileEncode,
        FilePondPluginFileValidateType,
        FilePondPluginImageExifOrientation,
        FilePondPluginImagePreview,
        FilePondPluginImageCrop,
        FilePondPluginImageResize,
        FilePondPluginImageTransform
        // add it here
);
```

**Comment by achyutgauli** [comment]
Is it    FilePondPluginFilePoster Or something else

**Comment by achyutgauli** [comment]
Just using laravel, I was able to see store image using input type but after using filepond preview is seen just after clicking on browser... I just want to see preview by default while using login to their profile section and store new image after user change it.

For your support: thank's in advance

**Comment by rikschennink** [comment]
You need to load the file poster plugin.
https://pqina.nl/filepond/docs/patterns/plugins/file-poster/

**Comment by achyutgauli** [comment]
Thank you so much preview is working fine automatically but using laravel, new image has stored but after using filepond, not worked so how can I stored new image on my localhost after clicking save button, which I have.

**Comment by achyutgauli** [comment]
![filepond](https://user-images.githubusercontent.com/21071463/49325767-d5af2380-f56f-11e8-9003-d003c1bbea15.png)

**Comment by achyutgauli** [comment]
I just want to "update profile image via filepond" if user wishes to change through filepond using save button. Note:: it's working fine without using filepond... But I want filepond on my client project for saving purpose help me.

**Comment by rikschennink** [comment]
I don’t have any experience with Laravel, you can check the PHP boilerplate to see how the server should accept the files.
https://github.com/pqina/filepond-boilerplate-php

**Comment by exninja** [comment]
@achyutgauli 

I'm also using Laravel, Vue, and FIlePond.
Hopefully the following will help. This is working for me on a drag and drop FilePond image, but should help connect the dots. 
I'm only on my second day using FilePond and still new to Vue, so there's probably room for improvement.

In my parent component I'm setting the FilePond "files" before loading the FilePond component.
This is so FilePond can load a pre-saved image if it exists.
```
<file-pond-upload :pondfiles="pondfiles" @imageupdate="updateImage"></file-pond-upload>
...
    methods: {
        loadData() {
            ...
            this.item = response.data;
            // prepare files prop for FilePond
            if (this.item.image_id) {
                this.pondfiles = [{ source: this.item.image_id, options: { type: 'local' }}];
            } else {
                this.pondfiles = [];
            }
        },
        updateImage(imageid) {
            // Process the returned imageid. e.g.
            this.hiddenformid = imageid;
        }
    }

```

In the FilePond component use @processfile callback to get the ID for your uploaded file.
@removefile can also be used to handle removing a file from the server if needed.
FilePondUpload.vue:

```
    <file-pond
        name="filepond"
        ref="pond"
        :files="pondfiles"
        @init="handleFilePondInit"
        @processfile="handleProcessedFile"
        @removefile="handleRemovedFile"
        :server="server"
        ...
    />
```

The FilePond ProcessedFile callback - use this to get the image id returned from your server.
In this case, I'm emitting the id back to my parent component for handling. 
You could then use this to put the id as a hidden field in your save form.
FilePondUpload.vue:
```
    methods: {
        handleFilePondInit: function() { ... },
        handleProcessedFile: function(error, file) {
            this.$emit('imageupdate', file.serverId); // send new image id to parent
            ...
        },
        handleRemovedFile: function(file) {
            this.$emit('imageupdate', ''); // send blank image id back to parent
            ...
        }
    }
```

FilePond processes to upload the file to the server.
I've included load & remove declarations here just as addn. info.
I'm including csrf token in the headers for the non-axios calls so Laravel doesn't reject it.

FilePondUpload.vue:
```
    props: ['pondfiles'],
    data() {
        return {
            server: {
                process: { 
                    url: '/api/processimage/',
                    headers: { 
                        'X-Requested-With': 'XMLHttpRequest',
                        'X-CSRF-TOKEN': token.content
                    }
                },
                load: {
                    url: '/api/loadimage/',
                    headers: { 
                        'X-Requested-With': 'XMLHttpRequest',
                        'X-CSRF-TOKEN': token.content
                    }
                },
                remove: (source, load, error) => {
                    axios.delete('/api/removeimage/' + source)
                        .then(response => {
                            // handle success response.data
                            // but see handleRemovedFiles method
                        })
                        .catch(error => {
                            // handle error.response
                            let message = error.response.data.message;
                            error(message);
                        });

                    // Call the load method when done
                    load();
                },
                revert: null,
                restore: null,
                fetch: null
            }
        };
    },
```

Declare a csrf token as Laravel will reject the process call without it.
In this case, I've already added it to my meta tags, so I'm pulling it in here.
FilePondUpload.vue:
```
let token = document.head.querySelector('meta[name="csrf-token"]');
```

Laravel Routes for my 3 FilePond calls:
Note that FilePond will append the server file ID to the load url, so the route here is valid.
In /routes/api.php:
```
Route::group(['middleware' => ['auth:api'], 'namespace' => 'Api', 'as' => 'api.'], function () {
...
    Route::post('processimage', 'ImageController@store');
    Route::get('loadimage/{image}', 'ImageController@show');
    Route::delete('removeimage/{id}', 'ImageController@destroy');
...
});
```

Laravel Controller methods for the 3 routes:
```
    public function store(Request $request)
    {
        $file = $request->file('filepond'); // note: name must match <file-pond/> name in vue.
        $filename = Storage::put('avatars', $file);

        // My Image table
        $image = new Image();
        $image->filename = $filename;
        $image->user_id_created = Auth::id();
        $image->save();

        return $image->id;
    }

    public function show(Image $image)
    {
        // My Image model injected.

        $filepath = storage_path('App/' . $image->filename);
        // This will output the needed content-disposition and mime-type
        return response()->download($filepath, 'my-file.png', [], 'inline');

        // Also works, but more work
        // $content = Storage::get($image->filename);
        // $mimetype = Storage::mimeType($image->filename);
        // return response($content)
        //     ->withHeaders([
        //         'Content-Type' => $mimetype,
        //         'Content-Disposition' => 'inline; filename=my-file.png',
        //     ]);
    }

    public function destroy($id)
    {
        // Retrieve image
        $image = Image::FindOrFail($id);
        // delete from storage
        Storage::delete($image->filename);
        // delete from image file
        $image->delete();

        return response()->json('Deleted Successfully')->setStatusCode(200);
    }
```
