### ISSUE TITLE
How to upload to local strorage using sqlite?

### ISSUE THREAD

**Issue by mandaputtra** [pqina/vue-filepond#36]
I got a problem when uploading to local storage(online storage works fine), i cant figure it out how i do that since i'm not developing on web, but i use electron (desktop) instead.

Is there any server configuration that i could do to save files locally?  or how i should do that? 

Thanks, 

*I know this not an issue, tbh I'm still not sure about posting this, I'm feeling doubtful, and maybe this ruin the issues post and other contributors as well*

**Comment by rikschennink** [comment]
Hey! No worries excellent and interesting issue, love to learn about various stacks FilePond is used in.

What I’m wondering is if SQLite can store file objects?

**Comment by rikschennink** [comment]
I think you can set up [a custom processing method](https://pqina.nl/filepond/docs/patterns/api/server/#advanced), FilePond will send the file that needs to be processed there and you can then store it wherever you like and return a unique id. No need to use a server.

You can then also set up a custom load method to restore files from the system.
