### ISSUE TITLE
Set id from response

### ISSUE THREAD

**Issue by cherniavsky94w** [pqina/vue-filepond#37]
How can I add file name and set id from **onload**
```vue
<file-pond :server="{
      url:base,
      process: {
        url: api,
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${$store.getters.token}`
        },
        onload: onResponse,
        onerror: onError
    },
    revert,
    restore: null,
    load: null,
    fetch: null,
}/>
```
onResponse
```js
onResponse(r) {
      r = JSON.parse(r)
      let fileId = r.result[0].file_id
      this.uploaded.push(fileId)
      this.$emit('finish', fileId)
}
```
How set id for revert and how call revert for get deleted id?

**Thanks!**

**Comment by cherniavsky94w** [comment]
@rikschennink thanks!

**Comment by ricardoccpaiva** [comment]
@rikschennink where is the `uploaded` variable declared ?

**Comment by rikschennink** [comment]
I don’t know, it’s a custom implementation by OP.

**Comment by saeedegh** [comment]
i added  **cosole.log('test');**  in the onResponse() method but it doesen't display any thing in console after uploading file.can you help me?
