### ISSUE TITLE
Plugins are active in multiple vue components, even though used in only one component when accessed via router-link

### ISSUE THREAD

**Issue by shouryaps** [pqina/vue-filepond#38]
First of all, I would like to thank you for this awesome library :smile:

I'm facing issues with resize and crop plugins with vue-filepond. I have two Vue component files with file-pond component. One with these plugins and one without these two plugins. Everything works well if i access Vue components directly through URL, that is loading the whole page. But through vue route-link if I navigate to another vue component (which doesn't have these plugins). The other vue component, still shows these plugins active on the filepond component.

**First Vue component (ComponentOne.vue):**
 1) Importing the vue-filepond, plugins and making the component as follows:
```js
import vueFilePond from 'vue-filepond';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
import FilePondPluginImageCrop from 'filepond-plugin-image-crop';
import FilePondPluginImageResize from 'filepond-plugin-image-resize';
import FilePondPluginImageTransform from 'filepond-plugin-image-transform';
const FilePond = vueFilePond(FilePondPluginFileValidateType, FilePondPluginImagePreview, FilePondPluginFileValidateSize, FilePondPluginImageCrop, FilePondPluginImageResize, FilePondPluginImageTransform);
```
2) Using in the template:
```vue
<file-pond name="file_pond_1"
    v-bind:files="initial_files"
    class="filepond"
    maxFileSize = "2MB"
    accepted-file-types="image/jpeg, image/png"
    imagePreviewHeight = "200"
    imageCropAspectRatio = "1:1"
    imageResizeTargetWidth = "200"
    imageResizeTargetHeight = "200"
    imageResizeMode = "force"
    allowRevert = "false"
    />
```

**Second Vue Component (ComponentTwo.vue)**
1) Importing the vue-filepond, plugins and making the component as follows:
```js
import vueFilePond from 'vue-filepond';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
const FilePond = vueFilePond(FilePondPluginFileValidateType, FilePondPluginImagePreview, FilePondPluginFileValidateSize);
```
2) Using in the template:
```vue
<file-pond name="file_pond_2"
    v-bind:files="initial_files"
    class="filepond"
    maxFileSize = "2MB"
    accepted-file-types="image/jpeg, image/png"
    imagePreviewHeight = "200"
    allowRevert = "false"
    />
```

**Navigation Vue Component (NavComponent.vue)**
I'm using `<router-link>` in my navigation component to render these components in App.vue

I'm am facing this issue on Chrome in Mac OS and Ubuntu.

**Comment by rikschennink** [comment]
Hi! Thanks for using FilePond!

Internally the plugins are registered to the FilePond core and then are automatically made available everywhere (which is what happens in the `vueFilePond` function), for the vanilla JavaScript version this made sense but for the Vue version not so much.

I think the best solution (not the most beautiful) for now is to manually disable the plugins.

An update to the second component:
```vue
<file-pond name="file_pond_2"
    v-bind:files="initial_files"

    allowImageCrop="false"
    allowImageTransform="false"
    allowImageResize="false"

    class="filepond"
    maxFileSize = "2MB"
    accepted-file-types="image/jpeg, image/png"
    imagePreviewHeight = "200"
    allowRevert = "false"
    />
```

**Comment by shouryaps** [comment]
Okay, got it. thanks. This fixed the issue.
