### ISSUE TITLE
accepted-file-types prop doesn't work

### ISSUE THREAD

**Issue by mattrothenberg** [pqina/vue-filepond#39]
### Summary
I've noticed that when using the `accepted-file-types` prop, the resulting `<input type="file">` does not have an `accept` attribute that reflects what was passed through via the prop.

### How to reproduce
```html
<file-pond
          name="test"
          ref="pond"
          label-idle="Drop attachments here..."
          allow-multiple="true"
          accepted-file-types="application/pdf" :files="attachments"/>
```
### Expected behaviour
```html
<input accept="application/pdf" class="filepond--browser" type="file" id="filepond--browser-dlq7nemwv" aria-controls="filepond--assistant-dlq7nemwv" aria-labelledby="filepond--drop-label-dlq7nemwv" >
```
See: https://codepen.io/rikschennink/pen/EQOLYe

### Additional information
Interestingly enough, it looks like the parent-most `div` rendered by the component is getting the `accept` attribute, not the `input`.

![screen shot 2018-08-19 at 12 00 24 pm](https://user-images.githubusercontent.com/5148596/44310617-7ace3380-a3a7-11e8-995e-b864a8c24587.png)

| Environment  | Version
|------------- | -----------
| OS           | MacOS 
| Browser      | Chrome v68.0

**Comment by rikschennink** [comment]
Have you registered the file-validate-type plugin?

**Comment by mattrothenberg** [comment]
Nope, but that should do it. Thanks!

I'd be more explicit about this in the documentation. While the readme does state that plugins need to be installed separately, your sample Vue code, which comes above the plugin disclaimer, makes it look like `accepted-file-types` comes out of the box with this library.


```html
<file-pond
        name="test"
        ref="pond"
        label-idle="Drop files here..."
        allow-multiple="true"
        accepted-file-types="image/jpeg, image/png"
        server="/api"
        v-bind:files="myFiles"
        v-on:init="handleFilePondInit"/>
```
```js
// Import FilePond plugins
// Please note that you need to install these plugins separately
```

**Comment by rikschennink** [comment]
Good point, will update the docs.

**Comment by msoutopico** [comment]
> 
> 
> Have you registered the file-validate-type plugin?

I'm also having difficulties with this plugin, to accept a zip file that has a different extension. I was assuming the plugin is automatically registered when you create the component (in Vue), like this:

```
  import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
  const FilePond = vueFilePond(
          FilePondPluginFileValidateType
  );
```

After that, do I still need to add `  FilePond.registerPlugin(		FilePondPluginFileValidateType	);`?

Thanks. Manuel
