### ISSUE TITLE
running on Nuxt SSR

### ISSUE THREAD

**Issue by dionfananie** [pqina/vue-filepond#4]
i've try vue-filepond in nuxt but its get error. please make it running in nuxt

**Comment by rikschennink** [comment]
Hi! Can you provide additional details, for instance, what error is thrown, which browser version are you testing with? Do you have a public test case?

**Comment by rikschennink** [comment]
@dionfananie Both the FilePond core and the Image Preview plugin were not suitable for SSR, I've updated the packages yesterday, should now work properly.

**Comment by dionfananie** [comment]
Thank you :D !!

**Comment by cherniavsky94w** [comment]
Hi, can you send config exmpl for nuxt?
