### ISSUE TITLE
File type validation doesn't work

### ISSUE THREAD

**Issue by DTX-92** [pqina/vue-filepond#40]
### Summary
 ```
               <file-pond
                    name="filepond"
                    ref="pond"
                    label-idle="Drop files here..."
                    allow-multiple="true"
                    accepted-file-types="audio/mpeg"
                    v-on:init="handleFilePondInit"
                    v-on:addfile="handleFilePondAddFile"
                    v-on:processfile="handleFilePondProcessFile"/>
```

![image](https://user-images.githubusercontent.com/20479161/44599052-b4ef6900-a7dd-11e8-89f0-455a5419e4c5.png)

As you can see filter applies correct, but if try to upload mp3 file, it throws error about incorrect type.

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Browser      | Google Chrome 68.0.3440.106

**Comment by rikschennink** [comment]
Are you sure the mime type is correct. You can drop a file on the file input on this page and it'll show you the mime type:
https://codepen.io/rikschennink/pen/NzRvbj

**Comment by DTX-92** [comment]
Okay, it was audio/mp3. I thought audio/mpeg is all about mp3.. Thanks!
