### ISSUE TITLE
Is it possible to change error message?

### ISSUE THREAD

**Issue by DTX-92** [pqina/vue-filepond#41]
![image](https://user-images.githubusercontent.com/20479161/44619917-03ac0a00-a895-11e8-8378-80108bb691a4.png)

I tried to change onerror in server options but it didnt work:
```
setOptions({
    server: {
        url: '/admin/upload',
        process: {
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
            },
            onerror: res => {
                debugger
                return '123'
            },
        },
    },
})
```

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Browser      | Google Chrome 68.0.3440.106

**Comment by rikschennink** [comment]
Currently, there's no way to send the server error message or anything dynamic towards the error message in the file item.  The `onerror` data is however accessible in the processfile error event.

I'm working on a solution. Ideally, the server response would not be directly placed in the file. For instance, on a multi-language site, you might want to present the error in a different language than the server or the server might not know the language to return. It would be piped through a function that by default returns the error response from the server but can be replaced with a function that allows returning labels based on the error response.

**Comment by DTX-92** [comment]
I cant find error message In the processfille error event:
![image](https://user-images.githubusercontent.com/20479161/44633137-6d104380-a98f-11e8-98de-78550cd31ae8.png)

But response is `application/json':
`{"filepond":["The filepond must be a file of type: audio\/mpeg."]}`

**Comment by rikschennink** [comment]
Please let me know if this did the trick, will close for now as it has been reported to work correctly on the vanilla js version.

**Comment by DTX-92** [comment]
Yea, it works, thanks.
For matching elements its possible to post element id to server and place it to response too, i guess.

**Comment by rikschennink** [comment]
> For matching elements its possible to post element id to server and place it to response too, i guess.

I'm not sure what you mean by that, can you elaborate?

**Comment by DTX-92** [comment]
For example, im trying to upload 5 files and one of them fires error.
![image](https://user-images.githubusercontent.com/20479161/44672690-d779c000-aa31-11e8-9299-c89a83fad8c8.png)
And in `onerror` callback there is only error message and its impossible to find needed element and replace error message.

**Comment by rikschennink** [comment]
I'm not sure why you would need access to the element, that's what the `labelFileProcessingError` is for.

- Use `onerror` to filter the server response and only return the error related info you need within FilePond or your application.

- Use `labelFileProcessingError` to use the error info (partially returned by `onerror`) to determine what error message to show.

- If you need to run an action on an item you can use an event `v-on:processfile` will return the error or the file based on if the upload was successful

**Comment by DTX-92** [comment]
I'm still trying to figire out how i can change error message here :|
![image](https://user-images.githubusercontent.com/20479161/44716768-ec069880-aac3-11e8-93da-476bc280d631.png)

**Comment by rikschennink** [comment]
If you update the core FilePond library than you should be able to use `labelFileProcessingError` to do that.

```
npm install filepond@2.1.0 --save
```

**Comment by DTX-92** [comment]
Huh
I manually updated filepond dependency in vue-filepond package and everything worked! Thank You A Lot!

**Comment by rikschennink** [comment]
\o/

I still have to update the version of filepond in the Vue package, so manually updating the filepond dependency will allow you to bypass that and install the latest version.

**Comment by ayophanz** [comment]
![image](https://user-images.githubusercontent.com/24581584/94576877-707e0380-02a8-11eb-8d76-93571049f79a.png)
Hi How do I call custom error message, I want to call see image

**Comment by riliwanrabo** [comment]
const inputElement = document.querySelector('input[type="file"]');
        const pond = FilePond.create(inputElement);
        pond.setOptions({
            server: {
                process: {
                    url: '/upload',
                    onerror: (response) => {
                        console.log(response)
                    }
                },
                revert: '/upload/revert',
                headers: {
                    'Accept': 'application/json',
                    'X-CSRF-TOKEN': '{{ @csrf_token() }}'
                }
            }
        });

**Comment by riliwanrabo** [comment]
```
const inputElement = document.querySelector('input[type="file"]');
        const pond = FilePond.create(inputElement);
        pond.setOptions({
            server: {
                process: {
                    url: '/upload',
                    onerror: (response) => {
                        console.log(response)
                    }
                },
                revert: '/upload/revert',
                headers: {
                    'Accept': 'application/json',
                    'X-CSRF-TOKEN': '{{ @csrf_token() }}'
                }
            }
        });
```

**Comment by masterkain** [comment]
how can I use `labelFileProcessingError` in vue 3 composition api?

my setup:

```
const serverConfig = computed(() => ({
  url: import.meta.env.VITE_UPLOAD_BASE_URL,
  process: {
    onerror: (response) => {
      serverResponse = JSON.parse(response);
      console.log(serverResponse);
    }
  },
}));
```

```
file-pond(name='cloud' ref='pond' allowRevert="false" maxParallelUploads="6" v-bind:allow-multiple='true' accepted-file-types='audio/mpeg, audio/mp4, audio/mp3, audio/flac' :server='serverConfig' @init='handleFilePondeInit')
```

**Comment by ItsPierre** [comment]
Hi, I got the same problem and couldn't fix it with your answers.

I am using the Vue-adaption of filepond and if I try to set a function for the `labelFileProcessingError` I just get the error, that type check failed, because a `string` is expected.

Is this solution deprecated and if so, is there another solution for this?
