### ISSUE TITLE
Upload button not showing

### ISSUE THREAD

**Issue by rosnaib11** [pqina/vue-filepond#5]
I just follow this under example.

```vue
<template>
  <div id="app">
    
    <FilePond
        name="test"
        ref="pond"
        labelIdle="Drop files here..."
        allowMultiple="true"
        acceptedFileTypes="image/jpeg, image/png"
        v-bind:files="myFiles"
        v-on:init="handleFilePondInit"/>
    
  </div>
</template>

<script>
// Import Vue FilePond
import FilePond, { registerPlugin } from 'vue-filepond';

// Import FilePond styles
import 'filepond/dist/filepond.min.css';

// Register file type validation plugin
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
registerPlugin(FilePondPluginFileValidateType);

export default {
    name: 'app',
    data: function() {
        return { myFiles: ['index.html'] };
    },
    methods: {
        handleFilePondInit: function() {
            console.log('FilePond has initialized');
            
            // FilePond instance methods are available on `this.$refs.pond`
        }
    },
    components: {
        FilePond
    }
};
</script>
```

https://codepen.io/rikschennink/pen/WXavEx

![image](https://user-images.githubusercontent.com/26837762/38600463-c76848a6-3d96-11e8-9a31-dcb61dbaa32a.png)

**Comment by rikschennink** [comment]
Hi @rosnaib11, the upload button will not show if there's no `process` endpoint specified. You can do so using the `server` option. https://pqina.nl/filepond/docs/patterns/api/server/

I'll update the example to make this more obvious.

**Comment by rosnaib11** [comment]
Thanks, it should be `:server` on vue js it works

**Comment by rikschennink** [comment]
@chtsngn You need to define the `server` attribute. Either by setting a url or by supplying a [server configuration object](https://pqina.nl/filepond/docs/patterns/api/server/).

```vue
<template>
  <div id="app">

    <file-pond :server="myServer"/>

  </div>
</template>

<script>
// Import Vue FilePond and FilePond styles
import vueFilePond from 'vue-filepond';
import 'filepond/dist/filepond.min.css';

// Create component
const FilePond = vueFilePond();

export default {
    name: 'app',
    data: function() {
        return {
            server: {
                url: 'url-to-your-api'
            }
        };
    },
    components: {
        FilePond
    }
};
</script>
```

**Comment by chtsngn** [comment]
@rikschennink thanks for the answer. I tried these. It loads automatically at this time. I want to install it manually.

**Comment by rikschennink** [comment]
I'm not sure what you mean with "loads automatically" and "install manually".

**Comment by chtsngn** [comment]
Sorry, my bad. I want to upload manually with this button.

![screenshot](https://user-images.githubusercontent.com/18267195/47018942-9b73f900-d15e-11e8-9750-bc65a4e3a834.png)

**Comment by rikschennink** [comment]
@chtsngn To achieve that you can set `instantUpload` to `false`.

**Comment by safiullahsarhandi** [comment]
> Hi @rosnaib11, the upload button will not show if there's no `process` endpoint specified. You can do so using the `server` `:server` option. https://pqina.nl/filepond/docs/patterns/api/server/
> 
> I'll update the example to make this more obvious.

i just wanted to hide upload button option and your answer just saved my time

**Comment by safiullahsarhandi** [comment]
> Hi @rosnaib11, the upload button will not show if there's no `process` endpoint specified. You can do so using the `server` `:server` option. https://pqina.nl/filepond/docs/patterns/api/server/
> 
> I'll update the example to make this more obvious.

i just wanted to hide upload button option and your answer just saved my time

**Comment by duyngha** [comment]
> @chtsngn To achieve that you can set `instantUpload` to `false`.

Thank you 👍 You saved my day.

**Comment by lohnsonok** [comment]
> @chtsngn To achieve that you can set `instantUpload` to `false`.

working for me. Thank a lot

**Comment by McGern** [comment]
Is it possible to have a single upload button that will trigger all files to upload, or do you have to roll your own using the output of the "onupdatefiles" prop?

**Comment by McGern** [comment]
@rikschennink Thanks for getting back so quickly. Just realised I posted this in vue-filepond instead of react-filepond, will it be a similar answer?

**Comment by McGern** [comment]
@rikschennink Just found out, sorry for asking first. If anyone else is here accidentally looking for react info, use useRef on the <FilePond> component and you can grab the processFiles off that.

const ref = useRef();

const handleUpload = () => {
  ref.current.processFiles();
}

return <FilePond ref={ref} .... />
