### ISSUE TITLE
How to get body response from server?

### ISSUE THREAD

**Issue by ppabcd** [pqina/vue-filepond#51]
Hello, i post image to backend server and server give json response. How to get body json response from filepond request?

**Comment by rikschennink** [comment]
You either set up your own [file processing method](https://pqina.nl/filepond/docs/patterns/api/server/) or you use the `onload` callback on the `server.process` property.

**Comment by aaveidt** [comment]
@rikschennink can you tell more detail about using `onload`?
if i parse json in `onload` method then how do i send data to `onprocessfile` ?
