### ISSUE TITLE
Dynamically adding new filepond instance triggers removefile event on all instances

### ISSUE THREAD

**Issue by theimerj** [pqina/vue-filepond#53]
Hello, first of all thank you for making such an incredible upload package. 

### Summary

When I add new instance of filepond (as can be seen on the video), other instances react by triggering removefile event. It could be probably connected to some hidden init method that checks other instances? 

Here is a gif showing the problem:

![screen-recording-2018-09-27-at-20 57 50](https://user-images.githubusercontent.com/5587309/46169198-abed2e00-c29a-11e8-9156-f2083e80d2d6.gif)

There is nothing fancy going on. The "modules" are looped with a v-for. \<file-upload\> is just a wrapper component.

```vue
<sortable-item v-for="module in modules" :key="module.id">
    <li class="draggable-item bg-white">
        <template v-if="module.type == 'text'">
            <div class="p-4">
                <quill-editor v-model="module.content" />
            </div>
        </template>
        <template v-else-if="module.type == 'image'">
            <div class="p-4">
                <file-upload
                    :options="{
                        name: 'file',
                        resource: 'media',
                        fileTypes: 'image/jpeg, image/png',
                        allowMultiple: false
                    }"
                    @send-files-array="storeFiles($event, module.id)"
                />
            </div>
        </template>
        <sortable-handle class="draggable-handle">
            x
        </sortable-handle>
        <button type="button" @click.prevent="removeModule(module.id)" class="delete">
            <i class="fa fa-times"></i>
        </button>
    </li>
</sortable-item>
```

Thank you very much for any help.

**Comment by rikschennink** [comment]
Ah yes that creates a shared options object, glad to hear it’s resolved and thanks for sharing the solution :-)
