### ISSUE TITLE
Can't seem to get image crop plugin to work

### ISSUE THREAD

**Issue by mikeskiddle** [pqina/vue-filepond#56]
### Summary
When using the vue.js adapter, I'm having trouble replicating the image crop/transform functionality as seen on the main project homepage

### How to reproduce
1. Install relevant packages
`npm install --save vue-filepond filepond-plugin-image-preview filepond-plugin-image-crop filepond-plugin-image-resize filepond-plugin-image-transform`

2. Import packages and create basic component
```javascript
<template>
    <section class="content-section col-12 col-lg-8">
        <section role="upload">
            <file-pond
            name="test"
            ref="pond"
            label-idle="Drop files here..."
            imageCropAspectRatio="1:1"
            allow-multiple="false"
            accepted-file-types="image/jpeg, image/png"
            server="http://localhost:3000/api"
            v-bind:files="myFiles"
            v-on:init="handleFilePondInit"
            imagePreviewHeight="170"
            imageResizeTargetWidth="200"
            imageResizeTargetHeight = "200"
            
            styleLoadIndicatorPosition="center bottom"
            styleProgressIndicatorPosition="right bottom"
            styleButtonRemoveItemPosition="left bottom"
            styleButtonProcessItemPosition="right bottom" />
        </section>
    </section>
</template>

<script>
import vueFilePond from "vue-filepond";
import "filepond/dist/filepond.min.css";
import "filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css";
import FilePondPluginImagePreview from "filepond-plugin-image-preview";
import FilePondPluginImageCrop from "filepond-plugin-image-crop";
import FilePondPluginImageResize from "filepond-plugin-image-resize";
import FilePondPluginImageTransform from "filepond-plugin-image-transform";

const FilePond = vueFilePond(
  FilePondPluginImagePreview,
  FilePondPluginImageCrop,
  FilePondPluginImageResize,
  FilePondPluginImageTransform
);

export default {
  name: "MyComponent",
  data: function() {
    return { myFiles: [] };
  },
  methods: {
    handleFilePondInit: function() {
      console.log("FilePond has initialized");
    }
  },
  components: {
    FilePond
  }
};
</script>
```

### Expected behaviour
When uploading an image, I was hoping to see the delete and crop images as seen in the profile picture demo at [https://pqina.nl/filepond/#examples](https://pqina.nl/filepond/#examples), however these options don't appear

### Additional information
I am trying to upload a 2000x2000 png image, which uploads fine.  My server route is pointing to an express.js endpoint which simply returns DONE.  There are no errors appearing in the console either

| Environment  | Version
|------------- | -----------
| OS          Mac OS 10.14
| Device       MacBook Pro 2017 edition
| Browser      Chrome 69.0.3497.100

**Comment by mikeskiddle** [comment]
The demo at [https://codepen.io/rikschennink/pen/EQOLYe](https://codepen.io/rikschennink/pen/EQOLYe) seems to replicate the above behaviour, in that it doesn't display any editing options after upload

**Comment by rikschennink** [comment]
Hi @mikeskiddle the edit button and editor are managed by the [Image Editor plugin](https://pqina.nl/filepond/image-editor.html) which I now see have forgotten to add to the `registerPlugin` call in the code example. Will update the example code. Sorry for the confusion.
