### ISSUE TITLE
FilePond.setOptions is not a function

### ISSUE THREAD

**Issue by gimyboya** [pqina/vue-filepond#57]
### Summary

I can't seem to use this syntax when using `vue-filepound` with typescript to set a custom process function

```typescript
FilePond.setOptions({
    server: {
		process(fieldName: any, file: any, metadata: any, load: any, error: any, progress: any, abort: any) {

			// fieldName is the name of the input field
			// file is the actual file object to send
			console.log(fieldName, file, file.name);
			
			
			// Should expose an abort method so the request can be cancelled
			return {
			  abort: () => {
				// Let FilePond know the request has been cancelled
				abort();
			  },
			};
		}

    }
});
```

I am getting the error `FilePond.setOptions is not a function`

### How to reproduce

try to use `FilePond.setOptions();` on a vue sigle file compoenet

### Expected behavior

Set a custom process function that doesn't upload the files anywhere.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Browser      |  Chrome

**Comment by rikschennink** [comment]
With Vue `FilePond` is a component so this doesn't work.

This should work:
```js
import { vueFilePond, setOptions } from 'vue-filepond';

setOptions({
    server: { ... }
});
```

**Comment by gimyboya** [comment]
Thank you for the fast reply
following your advice i am writing this:

```typescript
import { vueFilePond, setOptions } from 'vue-filepond';
// Import FilePond styles
import 'filepond/dist/filepond.min.css';

const FilePond = vueFilePond(FilePondPluginFileValidateType);
setOptions({
    server: { // my implemenetation }
});
```

and I am getting the following error: `Uncaught TypeError: Object(...) is not a function` which is referring to this line `const FilePond = vueFilePond(FilePondPluginFileValidateType);`

also having a type definition file would be very handy for typescript users.

**Comment by rikschennink** [comment]
I'm sorry, made a mistake, `vueFilePond` is a default export while `setOptions` is a named export.

I've run a quick test and the following works:

```js
import vueFilePond, { setOptions } from 'vue-filepond';

setOptions({
  labelIdle: 'hello!'
})

```

I'm not very familiar with TypeScript so if you are, PRs are welcome.

**Comment by gimyboya** [comment]
Thank you it's working properly now

**Comment by icangku** [comment]
how about having many filepond and I want specifically setOptions

**Comment by icangku** [comment]
how to set specifically if i have many fileponds

**Comment by rikschennink** [comment]
@icangku you can set attributes on the component.

**Comment by icangku** [comment]
can u give examle for setting server options on each component?

**Comment by showbear86** [comment]
`	<FilePond
		ref="pond"
		name="printfiles"
		label-idle="Druckdaten hier hochladen..."
		allow-multiple="false"
		data-style-panel-layout="integrated"
		accepted-file-types="application/pdf"
		:server="serverOptions"
		chunk-uploads
		:chunk-size="1048576 * 5"
		chunk-force
	/>`

**Comment by nxmndr** [comment]
Please add this to the doc for the translations. Otherwise you get stuck with "FilePond.setOptions is not a function" error, if you apply this solution : https://github.com/pqina/filepond/issues/39#issuecomment-657052506
