### ISSUE TITLE
ignored header option

### ISSUE THREAD

**Issue by sandroden** [pqina/vue-filepond#64]
Hi, just new to filepond here... I'm trying to setup file-pond whit server. As I'm using axios I thought I could just send Authentication token, but it seems it's not sent. My configuration:

template:

```html
  <file-pond
    v-model="image"
    name="test"
    ref="pond"
    label-idle="Drop files here..."
    :allow-multiple="false"
    allow-file-encode="true"
    accepted-file-types="image/jpeg, image/png"
    :files="files"
    :server="serverOptions"
    @init="handleFilePondInit"
  />

```
The serverOptions:

```javascript
data () {
    return {
      serverOptions: {
        headers: {
          'Authorization': 'JWT ' + this.token,
          'x-access-token': this.token,
        },
        url: 'http://127.0.0.1:8000/api/fp/',
        process: './process/',
        revert: './revert/',
        restore: './restore/',
        load: './load/',
        fetch: './fetch/',
      },
    }
```
My django server (using django_drf_filepond, but that doesn't get touched) refuses as no authentication is passed and inspecting with firefox I see no Authentication header.

One more issue is that if I don't declare the `process` directive it doesn't add /process to the URL while reading the docs I was convinced it should.

### Summary
headers do not appear to be honored. I don't know if it's vue-filepond or filepond
### Additional information

| Environment  | Version
|------------- | -----------
| OS           |  Linux 
| Browser      | firefox
|vue-filepond|4.0.2 
"filepond|3.6

**Comment by rikschennink** [comment]
Hi!

At the moment headers need to be configured per end-point. This should work:

```javascript
data () {
    return {
      serverOptions: {
        url: 'http://127.0.0.1:8000/api/fp/',
        process: {
            url: './process/',
            headers: {
                'Authorization': 'JWT ' + this.token,
                'x-access-token': this.token,
            }
        },
        revert: './revert/',
        restore: './restore/',
        load: './load/',
        fetch: './fetch/',
      },
    }
```

**Comment by sandroden** [comment]
Thanks, Rik, it works! I was convinced I already tried but now I realize it works. Really I get a different error: "Invalid request data has been provided." but that's a different error that I'll start to investigate. I'd say this issue is closed. Thanks for your help and for the very rich library.

**Comment by rikschennink** [comment]
Glad to hear that, and you're most welcome! :-)

Happy holidays @sandroden!
