### ISSUE TITLE
vue-filepond with toast-ui.vue-image-editor

### ISSUE THREAD

**Issue by HT-Moh** [pqina/vue-filepond#67]
Hello 

I am trying to integrate toast-ui.vue-image-editor using vue, I tried to follow the example with Doka.js and adapted to  toast-ui.vue-image-editor but I am getting error : 
 Uncaught TypeError: Object(...) is not a function, I think it's related to the create func that it's imported from vue-filepond. 
Can you please help? thank you in advance. 

```js
import { vueFilePond, create } from 'vue-filepond'
// import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type'
// Import FilePond styles
import 'filepond/dist/filepond.min.css'
// Import image preview plugin styles
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css'
import { uploadSvc } from '../services/file-upload-svc.js'

// Import image preview and file type validation plugins
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type'
import FilePondPluginImagePreview from 'filepond-plugin-image-preview'
import { ImageEditor } from '@toast-ui/vue-image-editor'
// Import the plugin code
import FilePondPluginImageEdit from 'filepond-plugin-image-edit'
// Import the plugin styles
// import 'filepond-plugin-image-edit/dist/filepond-plugin-image-edit.css';
// Create component
const FilePond = vueFilePond(
  FilePondPluginFileValidateType,
  FilePondPluginImagePreview,
  FilePondPluginImageEdit
)

create(document.querySelector('input'), {
  // default crop aspect ratio
  imageCropAspectRatio: 1,
  // resize to width of 200
  imageResizeTargetWidth: 200,
  // open editor on image drop
  imageEditInstantEdit: true,
  imageEditEditor: ImageEditor
})
```

**Comment by rikschennink** [comment]
The `imageEditEditor` property expects the supplied image editor to return a specific API, it's highly unlikely `toast-ui.vue-image-editor` conforms to this API.

At the moment the image-editor plugin is mostly there to make it easy to integrate [Doka](https://pqina.nl/doka).

**Comment by sandroden** [comment]
Hi Rik, I guess this means there's no point in using filepond if one needs editing capability and cannot afford to buy Doka... correct?

**Comment by rikschennink** [comment]
Not perse. You could open an image editor in the `server.process` callback. Or write a custom plugin that integrates with another editor. Or write a wrapper around another image editor plugin so it integrates with the image-edit plugin. Lot's of ways to go about it.

**Comment by rikschennink** [comment]
I've added some more info to the docs to make it easier to integrate with other editors:
https://pqina.nl/filepond/docs/patterns/plugins/image-edit/#integrating-other-editors
