### ISSUE TITLE
File Preview through dynamic image from database in Vuejs

### ISSUE THREAD

**Issue by JayU9769** [pqina/vue-filepond#75]
Hi guz,

I have used filepond for the file upload functionality. but now i want to preview image dynmically from the database so how i can preview images with plugin

i have used Vuejs and filepond component for that

```
<file-pond
       name="test"
       label-idle="Drop files here..."
       accepted-file-types="image/jpeg, image/png"
       allowImagePreview=true
        imagePreviewHeight="170"
        imageCropAspectRatio="1:1"
        imageResizeTargetWidth="200"
        imageResizeTargetHeight="200"
        stylePanelLayout="compact circle"
        styleLoadIndicatorPosition="center bottom"
        styleButtonRemoveItemPosition="center bottom"
        server="/api"
        v-bind:files="myFiles"
        v-on:init="handleFilePondInit"/>
```

**Comment by rikschennink** [comment]
You can use the image preview plugin
https://pqina.nl/filepond/docs/patterns/plugins/image-preview/

Use the `server.load` end-point to return file data required for the preview.
https://pqina.nl/filepond/docs/patterns/api/server/#load
