### ISSUE TITLE
Upload button outside 'file-pond' component

### ISSUE THREAD

**Issue by Vidhya-Dilip** [pqina/vue-filepond#79]
Is it possible to set a button outside 'file-pond' component to upload the file? Tried 'filepond--label-action' class. But it works only inside 'file-pond' component.

**Comment by pbowyer** [comment]
It is. I've added a method which I attach to my own button:
```
            onSubmit: function () {
                this.$refs.pond.processFiles().then(files => {
                    // files have been processed
                    console.log({files});
                });
            },
```
