### ISSUE TITLE
Module not found.

### ISSUE THREAD

**Issue by Lunberg88** [pqina/vue-filepond#8]
Have an issue. Doing all like in docs... But:

`  import FilePond, { registerPlugin } from 'vue-filepond';`
 ` import 'filepond/dist/filepond.min.css';`
 ` import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';`
  `registerPlugin(FilePondPluginFileValidateType);`

`    Module not found: Error: Can't resolve 'filepond-plugin-file-validate-type' in '/xxx/src/components'`

Any ideas?

**Comment by rikschennink** [comment]
Have you also installed the plugin using npm ? It sounds like it can’t find it.

**Comment by Lunberg88** [comment]
Yeah, i installed it via npm
`npm i vue-filepond -S`

**Comment by rikschennink** [comment]
The plugins need to be installed via npm as well, I’m looking into adding them as dependencies so they’re automatically downloaded.

**Comment by Lunberg88** [comment]
Its so strange... Doing all like on docs n have an error...

**Comment by rikschennink** [comment]
It’s possible that I made a mistake somewhere, if you upload your project somewhere (or make a test case) I’m happy to take a look when I get back from my vacation (~26th of April).

**Comment by rikschennink** [comment]
Will close for now as I haven't heard back,

**Comment by rikschennink** [comment]
@Hellek I'm testing this with `vue-cli` and it functions correctly whether I link directly to the `.esm` version or not.

```js
import vueFilePond from 'vue-filepond';

// Import plugins
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';

// Import styles
import 'filepond/dist/filepond.min.css';
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css';

// Create FilePond component
const FilePond = vueFilePond(FilePondPluginFileValidateType, FilePondPluginImagePreview);

```

**Comment by Hellek** [comment]
Definition of **RelatedFiles component**
```
import FilePond, { registerPlugin } from 'vue-filepond';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
import 'filepond/dist/filepond.min.css';
registerPlugin(FilePondPluginFileValidateType);

export default {
	name: "RelatedFiles",
	components: {
              FilePond
	}
```

If i include **RelatedFiles component** inside another component syncronous - there is no error
```
import RelatedFiles from "@/components/RelatedFiles";
export default {
	name: 'Order',
	components: {
		RelatedFiles
		// RelatedFiles: () => import("@/components/RelatedFiles") this cause webpack error which i show earlier
	}
```
This variant not cause webpack error, but file type check still not working. It's like just not exists

**Comment by rikschennink** [comment]
@Hellek The way the new Vue adapter component loads the plugins ( dynamically constructing the FilePond component ) is because otherwise the plugins might not load correctly. Best to switch.

**Comment by Hellek** [comment]
You mean "not include FilePond component and it's parents async"?

**Comment by rikschennink** [comment]
Should work async as well, but I do not have any experience with that. The best thing is to update to the latest version and test with that.

**Comment by rikschennink** [comment]
Thanks for the update @Hellek

**Comment by marcosalberto1991** [comment]
la mejor solución es mirar en la consola y me indica que debo instalar los siguiente paquetes  

npm install --save filepond-plugin-file-validate-type
npm install --save filepond-plugin-image-preview

en el manual oficial no muestra claramente los siguiente paquete que dedo instalar 

import vueFilePond from 'vue-filepond';

```
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';

// Import styles
import 'filepond/dist/filepond.min.css';
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css';

// Create FilePond component
const FilePond = vueFilePond( FilePondPluginFileValidateType, FilePondPluginImagePreview );
```
