### ISSUE TITLE
File metadata

### ISSUE THREAD

**Issue by creazy231** [pqina/vue-filepond#80]
### Summary
Using the plugin metadata causes in that I can't upload a file. After I chose an image using the file browser filepond reverts the upload. No progress - nothing.

### How to reproduce
`npm i filepond-plugin-file-metadata --save` and use it.

### Expected behaviour
A working plugin.

**Comment by rikschennink** [comment]
Can you give version `1.0.5` of the metadata plugin a try.

**Comment by creazy231** [comment]
Version `1.0.5` works like expected. Thanks ✨
