### ISSUE TITLE
Event callback processfileundo not called

### ISSUE THREAD

**Issue by phlegx** [pqina/vue-filepond#83]
Hi,

I have setup **vue-filepond 5.0.0** (v5.1.0 is not on npm at this time) with the latest version of **filepond 4.3.5**. Using callback `processfileundo` don't seems to work. 

```html
<file-pond ... @processfileundo="onprocessfileundo"/>
```

**Comment by phlegx** [comment]
On the [online documentation](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/) the callback is named `onprocessfileundo` and in the code the callback is named `onprocessfilerevert`.

**Comment by rikschennink** [comment]
Forgot to publish `5.1.0` so just published it.

Please submit a pull request so the docs can be updated.
https://github.com/pqina/filepond-docs
