### ISSUE TITLE
remove method called when Vue.$destroyed called

### ISSUE THREAD

**Issue by Wifsimster** [pqina/vue-filepond#84]
Hi, i just noticed something really weird !

If i leave my Vue component "rapidly" the **remove()** method from filepond is called (and all my files are removed from server...)

So, i inspect the stack trace and i got : 
`
destroy (vue.js) > Vue.$destroy (vue.js) > beforeDestroy (vue-filepond.js:178) > destroy (filepond.js:9203) > dispatch (filepond.js:78) > ABORT_ALL (filepond.js:4265)
`

And **ABORT_ALL** fire **remove** method from filepond, except i'm just leaving my Vue component at this point. 

It's kind of a annoying to lose all my files because i just change page too rapidly :/

**Comment by rikschennink** [comment]
If the component is removed, so is FilePond, any ongoing processes are stopped.

**Comment by Wifsimster** [comment]
@rikschennink Yeah, i got this. But it's not what is happening here. When the component is removed filepond call remove() on all my instanciate files.

**Comment by Wifsimster** [comment]
@rikschennink I made this example to prove my point : https://codesandbox.io/embed/yv0v008mlx

Navigate through the two pages rapidly and look at the console.

**Comment by rikschennink** [comment]
Thanks, I'll try to get to this next week.

**Comment by rikschennink** [comment]
I just published FilePond core `4.3.6`, should solve the issue.

`npm i filepond@latest --save`

**Comment by rikschennink** [comment]
Hang on, this probably won't fully solve it.

**Comment by rikschennink** [comment]
Try `4.3.7`

**Comment by Wifsimster** [comment]
The bug seems to be fixed !
Thanks a lot :)
