### ISSUE TITLE
Why the `process` method in `server` was called only twice

### ISSUE THREAD

**Issue by profileCaren** [pqina/vue-filepond#86]
### Summary

The `process` method in option `server` will only be called twice.

![image](https://user-images.githubusercontent.com/16242633/57187871-3fb96380-6f28-11e9-8718-81b6d744339c.png)

As you can see, I've selected couple of images (more than 2). But only two of them were successfully uploaded (trigger `process` method).

### How to reproduce

Here is my code. I am trying to upload to S3. 

```js
<!-- template -->
<template>
  <div id="app">

    <!-- full configuration docs is here -->
    <!-- https://pqina.nl/filepond/docs/patterns/api/filepond-instance/ -->
    <file-pond
      name="test"
      ref="pond"
      label-idle="Drop files here..."
      allow-multiple="true"
      accepted-file-types="image/jpeg, image/png"
      :server="server"
      :instant-upload="false"
      v-bind:files="myFiles"
      :beforeAddFile="beforeAddFile"
      v-on:init="handleFilePondInit"
    />
  </div>
</template>
```

```js
// server 
  data() {
    return {
      S3_SDK_wrapper,
      myFiles: [],

      // this is an option of filepond, see https://pqina.nl/filepond/docs/patterns/api/server/
      server: {
        process: this.process
      }
    };
  },
```

```js
// process method, defined in the component's `methods`
process(fieldName, file, metadata, load, error, progress, abort) {
      // fieldName is the name of the input field
      // file is the actual file object to send
      console.count("called",file.name);
      const uploadParams = {
           ...
      };

      let request = this.S3_SDK_wrapper.S3.upload(uploadParams, {
        connectionTimeout: 10 * 60 * 1000, // 10 mins
        httpOptions: { timeout: 10 * 60 * 1000 } // 10 mins
      });

      request.on("httpUploadProgress", function(e) {
        console.log(e.loaded / e.total);
        progress(true, e.loaded, e.total);
      });

      
      request.send(async (err, res) => {
        console.log("??");
      });

      // Should expose an abort method so the request can be cancelled
      return {
        abort: () => {
          // This function is entered if the user has tapped the cancel button
          request.abort();

          // Let FilePond know the request has been cancelled
          abort();
        }
      };
    },
```

### Expected behaviour

All of them will be uploaded. 

### Additional information

The console log is in below:

![image](https://user-images.githubusercontent.com/16242633/57187855-02ed6c80-6f28-11e9-8be0-fc99b5433934.png)

| Environment  | Version
|------------- | -----------
| OS           | Windows 
| Device       | Desktop
| Browser      |  Chrome 73.036

**Comment by profileCaren** [comment]
The same behavior with edge browser.

**Comment by profileCaren** [comment]
I've forked a [sandbox](https://codesandbox.io/s/nnq9xk40?fontsize=14) from your demo and reproduced the problem. Please check this out.

**Comment by rikschennink** [comment]
You're not calling the `load` in your custom processing method. Please read server docs here:
https://pqina.nl/filepond/docs/patterns/api/server/

**Comment by profileCaren** [comment]
OK, My bad. 
I'll read it through. Thanks for your response.

**Comment by profileCaren** [comment]
And besides that, how do I upload a directory? I've read the docs and did not found it. Thanks :)

**Comment by profileCaren** [comment]
OK, simply drag a directory to it. I was thinking the whole directory is going to be displayed as a directory. (so it won't be slow when there are hundreds of files inside). Anyway, thanks for your great job!
