### ISSUE TITLE
Providing attributes in kebab-case as plugin options won't work

### ISSUE THREAD

**Issue by rayax86** [pqina/vue-filepond#9]
I observed that if this component is written in DOM template, then any attribute (which has to be in kebab-case) passed in as an option to plugins won't be recognised as this component's props, **thus will be not translated to camelCase and hence will be ignored in the core `filepond`**.

I guess the reason is when `import FilePond from 'vue-filepond'` is done, the `props` option has already been used to construct the Vue component that is being exported, so the later update triggered by plugin registration won't take effect.

**Comment by rikschennink** [comment]
@rayax86 I'm not sure what you're getting at, the example in the readme shows to use camelCase not kebab-case. Maybe I'm missing something here?

```vue
<FilePond
        name="test"
        ref="pond"
        labelIdle="Drop files here..."
        allowMultiple="true"
        acceptedFileTypes="image/jpeg, image/png"
        server="/api"
        v-bind:files="myFiles"
        v-on:init="handleFilePondInit"/>
```

**Comment by rayax86** [comment]
@rikschennink Thanks for the reply. The DOM template is the initial HTML rendered by the browser. You cannot use camelCase because HTML attributes are case insensitive. If an attribute passed to a Vue component **is recognised as a prop** and is in kebab-case, it will be translated to camelCase. Actually, the use of camelCase attributes is discouraged as per the official style guide: https://vuejs.org/v2/style-guide/#Prop-name-casing-strongly-recommended.

**Comment by rikschennink** [comment]
@rayax86 Aha! Thanks, looking into this right now.

**Comment by rikschennink** [comment]
@rayax86 I've updated the snippet in the readme and am updating the docs, but I can't really reproduce the problem, my test setup does load the additional plugin props correctly.

**Comment by rnunot** [comment]
Here is a demo that shows this issue: 
[https://codesandbox.io/s/wy351krxy8](https://codesandbox.io/s/wy351krxy8)

**Comment by rayax86** [comment]
@rikschennink So let's be sure that we are on the same page: did you set it up using DOM template? That is:

index.html
```
<html>
<body>
    <div id="app">
        <FilePond></FilePond>
    </div>
    <script src="/compiled-js.js"></script>
</body>
</html>
```
source-js.js
```
import Vue from 'Vue'

import FilePond, { registerPlugin } from 'vue-filepond';

import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
registerPlugin(FilePondPluginFileValidateType);

new Vue({
    el: '#app',
    components: {
        FilePond,
    },
})

**Comment by rayax86** [comment]
@rikschennink In fact, it doesn't matter whether you use DOM template or string template. As long as I don't write the attribute in camelCase, it will not be recognised by the plugins. If you do use string template, you would have the option to write the attribute in camelCase (against the style guide), thus bypassing the problem.

I have given the reason above: props added by plugin registrations won't take effect. So (template/HTML) attributes will be treated as (Vue) attrs, not (Vue) props, and will not be translated to camelCase.

The ultimate reason, as I said, is as soon as your script is run, the `FilePond` component is registered with the default props, so later calls to your `update` method (which updates the `props` variable) won't take effect.

**Comment by rikschennink** [comment]
@rnunot Thanks for the test case, super useful!

@rayax86 I'm looking at creating a higher order component, I think that should allow me to register the options before the component is actually created.

```js
import { withFilePondPlugins } from 'vue-filepond';

// Import styles
import 'filepond/dist/filepond.min.css';

// Register a plugin
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.esm.js';

export default {
    name: 'app',
    components: {
        FilePond: withFilePondPlugins(FilePondPluginFileValidateType)
    }
};
```

**Comment by rikschennink** [comment]
@rayax86 I see I might have made another error with the name of the component, it needs to be kebab case as well. `<file-pond>` instead of `<FilePond>`

**Comment by rikschennink** [comment]
@rnunot @rayax86 just published version `2.0.0` of the FilePond component.

The module now exports a function to create the FilePond component with. Docs and readme have been updated.

**Comment by rayax86** [comment]
@rikschennink Can confirm it is fixed.

**Comment by rikschennink** [comment]
@rayax86 Fantastic, thanks for confirming!
