### ISSUE TITLE
Vuex state as parameter for custom server

### ISSUE THREAD

**Issue by BorisKligman** [pqina/vue-filepond#91]
Hello!
There was a problem: the API requires additional parameters, including the json object. If I add parameters using FormData.append(), without reactive data, everything goes well. But when I try to add data from the computed property vuex, I get the error cannot read property of undefined. Is there a way to pass a vuex state in a filePond instance?

```js
setOptions({
  fileRenameFunction: file => new Promise(resolve => {
    resolve(window.prompt('Имя файла', file.name))
  }),
  server: {
    params: JSON.stringify({
          id_login: userData.id_login,
          id_patient: pickedOptions.id_patient,
          id_doc_type: pickedOptions.id_doc_type
    }),
    process:(fieldName, file, metadata, load, error, progress, abort) => {
      const formData = new FormData();
      formData.append(fieldName, file, file.name);
      formData.append('submit', 'upload')
      formData.append('json', `${params}`)
      const request = new XMLHttpRequest();
      request.open('POST', 'url');
      request.upload.onprogress = (e) => {
        progress(e.lengthComputable, e.loaded, e.total);
      };
      request.onload = function() {
        if (request.status >= 200 && request.status < 300) {
          load(request.responseText);
        }
        else {
          error('oh no');
        }
      };
      request.send(formData);
      return {
        abort: () => {
          request.abort();
          abort();
        }
      };
    }
  },
})
```

**Comment by rikschennink** [comment]
There probably is but as I am not an expert in Vuex I'm not sure. You could set those values as file metadata entries, that makes them available in the process method.

**Comment by BorisKligman** [comment]
When I tried to pass the value of the reactive variables directly to the server object of setOptions instance, this didn't match. Possibly, access of such level is not provided or intends to be closed.
My problem was solved when I delivered the process method directly to the Vue instance.
