### ISSUE TITLE
PDF, DOC, XLS miniatures.

### ISSUE THREAD

**Issue by oiagorodrigues** [pqina/vue-filepond#92]
Hi.

How can I add miniatures of the file types when the user uploads a file ?
I'm trying to use the `file poster` plugin to do that (using vue btw), but without success.

That's my code:

```
  <file-pond
      ref="pond"
      :files="upload"
      :allowMultiple="true"
      :allowBrowse="true"
      :allowDrop="true"
      :allowFilePoster="true"
      @addfilestart="onAddFile"
    />

  // importing plugins ...
  // apllying plugins ...

   onAddFile (file) {
      file.setMetadata('poster', require('../assets/icons/pdf.svg'))
    },
```

That was my lastest attempt. It adds the metadata to the file, but nothing happens in the screen. 

I tried to use a `png` file, instead of `svg`, but the result was the same.

I'll not upload the file right when I select one. I'll send it alongside with a form in a submit event.

**Comment by rikschennink** [comment]
the post plugin does not handle dynamic updates of the poster property so the poster image has to be set before the image shows. In this situation you'd have to write a custom plugin, forking the poster plugin and adjusting it is the best approach.
