### ISSUE TITLE
TypeError: Cannot read property 'getFiles' of null

### ISSUE THREAD

**Issue by alcaitiff** [pqina/vue-filepond#93]
### Summary

The versions 5.1.0 and 5.1.1 changed it to allow v-model support.

When the component refreshes it appears to lose reference to _pound and it fails emitting the input signal.

### How to reproduce

Put the component inside a v-for, when you upload or remove an uploaded file the error will appear on console.

The error occur on the line 153 of the file vue-filepound.js 

```javascript
_this.$emit('input', _this._pond.getFiles());
``` 

Apparently the object "_this._pond" is somehow null at this point when it is used inside a loop.

### Expected behaviour

No error on console

### Additional information

| Environment  | Version
|------------- | -----------
| OS           |   Linux
| Device       | PC
| Browser      | Chrome 75.0.3770.100

**Comment by rikschennink** [comment]
Please provide a test case on https://codesandbox.io/s/p3v8zoprp7

**Comment by alcaitiff** [comment]
Test case in: https://codesandbox.io/s/vue-filepond-live-demo-g5sj0

How to see it: 

1. open https://g5sj0.codesandbox.io/
2. open the console
3. add a file
4. remove the file
5. see the error
![s1](https://user-images.githubusercontent.com/14186387/61397444-48230880-a8a0-11e9-8685-cc904c3c478a.png)
![s2](https://user-images.githubusercontent.com/14186387/61397445-48230880-a8a0-11e9-8873-af2e0bff4e91.png)




open the console

**Comment by alcaitiff** [comment]
If you change the vue-filepond to version 4.0.3 there will be no error

**Comment by rikschennink** [comment]
This is happening because you're rebuilding the entire app on file remove (or somewhere in between). This causes the FilePond instance (and therefor ref) to be lost. It worked on 4.0.3 because that version contained a bug that would prevent FilePond from cleaning up its instance (resulting in memory leaks).

**Comment by alcaitiff** [comment]
Today I tried with version 5.0.0 and 5.1.0 on https://codesandbox.io and it worked fine.

The error only appears on 5.1.1

On this version this._pond is cleared when the component root node has been detached like you can see here https://github.com/pqina/vue-filepond/commit/4e69e906e395ff1e0acd8d57a8d4b286385b6b63#diff-8866a1d4bf3fb5bf78aa4bbc2b58e831

I'm not sure if this is really necessary.

If we really need to clear it, maybe we should add a test before using it. Something like

```js
if(_this.pond){
    _this.$emit('input', _this._pond.getFiles());
}else{
    //I don't know if is better emit null, empty array or does not emit at all
    _this.$emit('input', []);
}
```

**Comment by rikschennink** [comment]
It needs to be cleared otherwise the instance stays active and new instances could be created for each re-render.

**Comment by alcaitiff** [comment]
So what do you think about putting this test before emitting?

**Comment by rikschennink** [comment]
It's better than nothing. I'm just wondering why you're redrawing the component.

**Comment by alcaitiff** [comment]
Obviously the code I provided was just for test purposes and the application I'm working on is a lot more complex.

Basically I have some different lists of files that must be manipulated and the component must be used inside of a loop.

**Comment by rikschennink** [comment]
We could make it a bit shorter:

```js
this.$emit('input', this._pond ? this._pond.getFiles() : []);
```

**Comment by alcaitiff** [comment]
Sure thing. It's done.

**Comment by rikschennink** [comment]
Just publised 5.1.2
