### ISSUE TITLE
vue-filepond Doka.js

### ISSUE THREAD

**Issue by mauricebalde** [pqina/vue-filepond#96]
Hi there,

unfortunately the docs lack any detail on using the Doka.js inside vue.
I bought the license and setup Doka and filepond each aside working fine.
but I can't find a way to trigger Doka from filepond inside vue.
Also the edit image button in the bottom center is always missing.

<template>
    <div id="app">
        <div>
            <FilePond
                    name="test"
                    ref="pond"
                    instantUpload=instantUpload
                    accepted-file-types="image/jpeg, image/png"
                    styleLoadIndicatorPosition="bottom center"
                    styleProgressIndicatorPosition="right bottom"
                    styleButtonRemoveItemPosition="left bottom"
                    styleButtonProcessItemPosition="right bottom"
                    styleImageEditButtonEditItemPosition="bottom center"
                    allowmultiple="false"
                    style-panel-layout="compact circle"
                    labelIdle="hey hey up it!"
                    labelFileProcessing="Storing media"
                    server="http://192.168.33.10"
                    imageEditEditor=" Doka.create({})"
                                   />
        
        </div>
    </div>
</template>
<script>
    import * as FilePond from 'filepond';
    import vueFilePond from 'vue-filepond';
    import 'filepond/dist/filepond.min.css';
    import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
    import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css';
    import FilePondPluginImageEdit from 'filepond-plugin-image-edit';
    import 'filepond-plugin-image-edit/dist/filepond-plugin-image-edit.css';

    FilePond.registerPlugin(FilePondPluginImageEdit);

    export default {
        name: 'app',
        components: {
            FilePond: vueFilePond(FilePondPluginImagePreview)
        },
    }
</script>

**Comment by rikschennink** [comment]
Hi @mauricebalde, 

Your Doka product license ships with personal support please use the support form over at https://pqina.nl/doka/support/ happy to help out.

I'll update the package with a Vue + FilePond + Doka integration example.

This should do it:

```vue
<template>
  <div id="app">

    <file-pond
        name="test"
        ref="pond"
        server="/api"
        v-bind:imageEditEditor="myDoka"
        v-bind:files="myFiles"
        v-on:init="handleFilePondInit"/>

  </div>
</template>

<script>
// Import Doka
import { create } from './doka/doka.esm.min';
import './doka/doka.min.css';

// Import Vue FilePond
import vueFilePond from 'vue-filepond';

// Import FilePond styles
import 'filepond/dist/filepond.min.css';

// Import FilePond plugins
// Please note that you need to install these plugins separately

// Import image preview plugin styles
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css';
import 'filepond-plugin-image-edit/dist/filepond-plugin-image-edit.min.css';

// Import image preview and file type validation plugins
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
import FilePondPluginImageEdit from 'filepond-plugin-image-edit';

// Create component
const FilePond = vueFilePond(FilePondPluginImagePreview, FilePondPluginImageEdit);

export default {
    name: 'app',
    data: function() {
        return {
            myFiles: ['cat.jpeg'],
            myDoka: create({
                // doka options here
            })
        };
    },
    methods: {
        handleFilePondInit: function() {
            console.log('FilePond has initialized');

            // FilePond instance methods are available on `this.$refs.pond`
        }
    },
    components: {
        FilePond
    }
};
</script>
```
