### ISSUE TITLE
Drag event listeners

### ISSUE THREAD

**Issue by dzotos** [pqina/vue-filepond#97]
Hi, first of all you made an amazing work with this uploader, big thanks!

On my question. Is there any way of capturing drag events of type eg. "dragover, dragend"? What I'm trying to achieve is, to manipulate the styles/classes from the drop area while listening on this events. It seems that there is no way to achieve this atm, rather set the event listeners manually.

**Comment by rikschennink** [comment]
FilePond toggles a `data-hopper-state` attribute on the `.filepond--root` element (`drag-exit`, `drag-over`). Maybe you can use that to style the drop area?

**Comment by dzotos** [comment]
@rikschennink Thanks for the reply. You are right but, this state changes when you hover the drop area. I need to be triggered when something is dragged within the page.

**Comment by rikschennink** [comment]
Ah, I think that would require adding additional listeners.

**Comment by dzotos** [comment]
Cool, thanks 👍

**Comment by wengtytt** [comment]
Need that as well~
